#!/bin/bash

JAVA_BIN=/usr/bin/java
BDU_API_CLIENT=/home/smcadmin/bin/BDUAPIClient.jar
BDU_PRODUCER_MODE="-m stream-publish"

if [[ $# -lt 3 ]]; then
	echo "usage: $0 <server> <topic> <message> <message brokers> <error directory>"
	exit 1
fi

TOPIC="-t %2Fstreams%2Fsmcstream%3A$2"
KAFKA_SERVER="-ks $1"
MSG="-msg $3"

DEFAULT_DIR="-Dconsume.dir=file:///tmp/bduapiclient?noop=true"
DEFAULT_PRODUCER="-Dkafka.producer.config=kafka:$1?topic=%2Fstreams%2Fsmcstream%3A$2"
producer_brokers="-Dproducer.brokers=$4"
error_dir="-Derror.landing.dir=file://$5"

exec $JAVA_BIN $DEFAULT_DIR $DEFAULT_PRODUCER $error_dir -jar $BDU_API_CLIENT $BDU_PRODUCER_MODE $TOPIC $KAFKA_SERVER $MSG
