//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.22 at 01:33:26 AM SGT 
//


package com.bcd.bdu.model.accounts;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Account" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="GCN" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                   &lt;element name="SMId" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *                   &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ReportingTree" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ReportingRemarks" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ReportingRemark" type="{}ReportingRemarkType" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ReasonCodes" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ReasonCode" type="{}ReasonCodeType" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="SavingsComparisons" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="SavingsComparison" type="{}SavingsComparisonType" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "account"
})
@XmlRootElement(name = "Accounts")
public class Accounts {

    @XmlElement(name = "Account", required = true)
    protected List<Accounts.Account> account;

    /**
     * Gets the value of the account property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the account property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Accounts.Account }
     * 
     * 
     */
    public List<Accounts.Account> getAccount() {
        if (account == null) {
            account = new ArrayList<Accounts.Account>();
        }
        return this.account;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="GCN" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *         &lt;element name="SMId" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
     *         &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ReportingTree" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ReportingRemarks" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ReportingRemark" type="{}ReportingRemarkType" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ReasonCodes" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ReasonCode" type="{}ReasonCodeType" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="SavingsComparisons" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="SavingsComparison" type="{}SavingsComparisonType" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "gcn",
        "smId",
        "countryCode",
        "name",
        "reportingTree",
        "reportingRemarks",
        "reasonCodes",
        "savingsComparisons"
    })
    public static class Account {

        @XmlElement(name = "GCN")
        @XmlSchemaType(name = "unsignedShort")
        protected int gcn;
        @XmlElement(name = "SMId")
        @XmlSchemaType(name = "unsignedInt")
        protected Long smId;
        @XmlElement(name = "CountryCode")
        protected String countryCode;
        @XmlElement(name = "Name")
        protected String name;
        @XmlElement(name = "ReportingTree")
        protected String reportingTree;
        @XmlElement(name = "ReportingRemarks")
        protected Accounts.Account.ReportingRemarks reportingRemarks;
        @XmlElement(name = "ReasonCodes")
        protected Accounts.Account.ReasonCodes reasonCodes;
        @XmlElement(name = "SavingsComparisons")
        protected Accounts.Account.SavingsComparisons savingsComparisons;

        /**
         * Gets the value of the gcn property.
         * 
         */
        public int getGCN() {
            return gcn;
        }

        /**
         * Sets the value of the gcn property.
         * 
         */
        public void setGCN(int value) {
            this.gcn = value;
        }

        /**
         * Gets the value of the smId property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getSMId() {
            return smId;
        }

        /**
         * Sets the value of the smId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setSMId(Long value) {
            this.smId = value;
        }

        /**
         * Gets the value of the countryCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountryCode() {
            return countryCode;
        }

        /**
         * Sets the value of the countryCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountryCode(String value) {
            this.countryCode = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the reportingTree property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReportingTree() {
            return reportingTree;
        }

        /**
         * Sets the value of the reportingTree property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReportingTree(String value) {
            this.reportingTree = value;
        }

        /**
         * Gets the value of the reportingRemarks property.
         * 
         * @return
         *     possible object is
         *     {@link Accounts.Account.ReportingRemarks }
         *     
         */
        public Accounts.Account.ReportingRemarks getReportingRemarks() {
            return reportingRemarks;
        }

        /**
         * Sets the value of the reportingRemarks property.
         * 
         * @param value
         *     allowed object is
         *     {@link Accounts.Account.ReportingRemarks }
         *     
         */
        public void setReportingRemarks(Accounts.Account.ReportingRemarks value) {
            this.reportingRemarks = value;
        }

        /**
         * Gets the value of the reasonCodes property.
         * 
         * @return
         *     possible object is
         *     {@link Accounts.Account.ReasonCodes }
         *     
         */
        public Accounts.Account.ReasonCodes getReasonCodes() {
            return reasonCodes;
        }

        /**
         * Sets the value of the reasonCodes property.
         * 
         * @param value
         *     allowed object is
         *     {@link Accounts.Account.ReasonCodes }
         *     
         */
        public void setReasonCodes(Accounts.Account.ReasonCodes value) {
            this.reasonCodes = value;
        }

        /**
         * Gets the value of the savingsComparisons property.
         * 
         * @return
         *     possible object is
         *     {@link Accounts.Account.SavingsComparisons }
         *     
         */
        public Accounts.Account.SavingsComparisons getSavingsComparisons() {
            return savingsComparisons;
        }

        /**
         * Sets the value of the savingsComparisons property.
         * 
         * @param value
         *     allowed object is
         *     {@link Accounts.Account.SavingsComparisons }
         *     
         */
        public void setSavingsComparisons(Accounts.Account.SavingsComparisons value) {
            this.savingsComparisons = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ReasonCode" type="{}ReasonCodeType" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "reasonCode"
        })
        public static class ReasonCodes {

            @XmlElement(name = "ReasonCode")
            protected List<ReasonCodeType> reasonCode;

            /**
             * Gets the value of the reasonCode property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the reasonCode property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getReasonCode().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ReasonCodeType }
             * 
             * 
             */
            public List<ReasonCodeType> getReasonCode() {
                if (reasonCode == null) {
                    reasonCode = new ArrayList<ReasonCodeType>();
                }
                return this.reasonCode;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ReportingRemark" type="{}ReportingRemarkType" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "reportingRemark"
        })
        public static class ReportingRemarks {

            @XmlElement(name = "ReportingRemark")
            protected List<ReportingRemarkType> reportingRemark;

            /**
             * Gets the value of the reportingRemark property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the reportingRemark property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getReportingRemark().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ReportingRemarkType }
             * 
             * 
             */
            public List<ReportingRemarkType> getReportingRemark() {
                if (reportingRemark == null) {
                    reportingRemark = new ArrayList<ReportingRemarkType>();
                }
                return this.reportingRemark;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="SavingsComparison" type="{}SavingsComparisonType" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "savingsComparison"
        })
        public static class SavingsComparisons {

            @XmlElement(name = "SavingsComparison")
            protected List<SavingsComparisonType> savingsComparison;

            /**
             * Gets the value of the savingsComparison property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the savingsComparison property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSavingsComparison().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link SavingsComparisonType }
             * 
             * 
             */
            public List<SavingsComparisonType> getSavingsComparison() {
                if (savingsComparison == null) {
                    savingsComparison = new ArrayList<SavingsComparisonType>();
                }
                return this.savingsComparison;
            }

        }

    }

}
