//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.22 at 01:33:26 AM SGT 
//


package com.bcd.bdu.model.accounts;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Accounts }
     * 
     */
    public Accounts createAccounts() {
        return new Accounts();
    }

    /**
     * Create an instance of {@link ReportingRemarkType }
     * 
     */
    public ReportingRemarkType createReportingRemarkType() {
        return new ReportingRemarkType();
    }

    /**
     * Create an instance of {@link SavingsComparisonType }
     * 
     */
    public SavingsComparisonType createSavingsComparisonType() {
        return new SavingsComparisonType();
    }

    /**
     * Create an instance of {@link Accounts.Account }
     * 
     */
    public Accounts.Account createAccountsAccount() {
        return new Accounts.Account();
    }

    /**
     * Create an instance of {@link OtherSavingsComparisonType }
     * 
     */
    public OtherSavingsComparisonType createOtherSavingsComparisonType() {
        return new OtherSavingsComparisonType();
    }

    /**
     * Create an instance of {@link LookupType }
     * 
     */
    public LookupType createLookupType() {
        return new LookupType();
    }

    /**
     * Create an instance of {@link ReasonCodeType }
     * 
     */
    public ReasonCodeType createReasonCodeType() {
        return new ReasonCodeType();
    }

    /**
     * Create an instance of {@link ReportingRemarkType.Lookups }
     * 
     */
    public ReportingRemarkType.Lookups createReportingRemarkTypeLookups() {
        return new ReportingRemarkType.Lookups();
    }

    /**
     * Create an instance of {@link SavingsComparisonType.GlobalAirSavingsComparison }
     * 
     */
    public SavingsComparisonType.GlobalAirSavingsComparison createSavingsComparisonTypeGlobalAirSavingsComparison() {
        return new SavingsComparisonType.GlobalAirSavingsComparison();
    }

    /**
     * Create an instance of {@link SavingsComparisonType.GlobalAuxiliarySavingsComparison }
     * 
     */
    public SavingsComparisonType.GlobalAuxiliarySavingsComparison createSavingsComparisonTypeGlobalAuxiliarySavingsComparison() {
        return new SavingsComparisonType.GlobalAuxiliarySavingsComparison();
    }

    /**
     * Create an instance of {@link SavingsComparisonType.LowFareSavings }
     * 
     */
    public SavingsComparisonType.LowFareSavings createSavingsComparisonTypeLowFareSavings() {
        return new SavingsComparisonType.LowFareSavings();
    }

    /**
     * Create an instance of {@link SavingsComparisonType.ReferenceFare }
     * 
     */
    public SavingsComparisonType.ReferenceFare createSavingsComparisonTypeReferenceFare() {
        return new SavingsComparisonType.ReferenceFare();
    }

    /**
     * Create an instance of {@link SavingsComparisonType.DollarSavings }
     * 
     */
    public SavingsComparisonType.DollarSavings createSavingsComparisonTypeDollarSavings() {
        return new SavingsComparisonType.DollarSavings();
    }

    /**
     * Create an instance of {@link SavingsComparisonType.AuxiliarySavingsComparison }
     * 
     */
    public SavingsComparisonType.AuxiliarySavingsComparison createSavingsComparisonTypeAuxiliarySavingsComparison() {
        return new SavingsComparisonType.AuxiliarySavingsComparison();
    }

    /**
     * Create an instance of {@link SavingsComparisonType.OtherSavingsComparisons }
     * 
     */
    public SavingsComparisonType.OtherSavingsComparisons createSavingsComparisonTypeOtherSavingsComparisons() {
        return new SavingsComparisonType.OtherSavingsComparisons();
    }

    /**
     * Create an instance of {@link Accounts.Account.ReportingRemarks }
     * 
     */
    public Accounts.Account.ReportingRemarks createAccountsAccountReportingRemarks() {
        return new Accounts.Account.ReportingRemarks();
    }

    /**
     * Create an instance of {@link Accounts.Account.ReasonCodes }
     * 
     */
    public Accounts.Account.ReasonCodes createAccountsAccountReasonCodes() {
        return new Accounts.Account.ReasonCodes();
    }

    /**
     * Create an instance of {@link Accounts.Account.SavingsComparisons }
     * 
     */
    public Accounts.Account.SavingsComparisons createAccountsAccountSavingsComparisons() {
        return new Accounts.Account.SavingsComparisons();
    }

}
