//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.22 at 01:33:26 AM SGT 
//


package com.bcd.bdu.model.accounts;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for OtherSavingsComparisonType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OtherSavingsComparisonType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SavingsComparisonName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OtherSavingsComparisonName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Countries" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SavingsComparisonType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OtherSavingsComparisionSourceofData" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OtherSavingsComparisonRequired" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OtherSavingComparisonDefinition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OtherSavingComparisionadditionalnote" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FareSavingsTest" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LastModifiedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="OtherSavingsComparisonNotes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OtherSavingsComparisonType", propOrder = {
    "name",
    "savingsComparisonName",
    "otherSavingsComparisonName",
    "countries",
    "savingsComparisonType",
    "otherSavingsComparisionSourceofData",
    "otherSavingsComparisonRequired",
    "otherSavingComparisonDefinition",
    "otherSavingComparisionadditionalnote",
    "fareSavingsTest",
    "lastModifiedDate",
    "otherSavingsComparisonNotes"
})
public class OtherSavingsComparisonType {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "SavingsComparisonName", required = true)
    protected String savingsComparisonName;
    @XmlElement(name = "OtherSavingsComparisonName", required = true)
    protected String otherSavingsComparisonName;
    @XmlElement(name = "Countries", required = true)
    protected String countries;
    @XmlElement(name = "SavingsComparisonType", required = true)
    protected String savingsComparisonType;
    @XmlElement(name = "OtherSavingsComparisionSourceofData", required = true)
    protected String otherSavingsComparisionSourceofData;
    @XmlElement(name = "OtherSavingsComparisonRequired", required = true)
    protected String otherSavingsComparisonRequired;
    @XmlElement(name = "OtherSavingComparisonDefinition", required = true)
    protected String otherSavingComparisonDefinition;
    @XmlElement(name = "OtherSavingComparisionadditionalnote", required = true)
    protected String otherSavingComparisionadditionalnote;
    @XmlElement(name = "FareSavingsTest", required = true)
    protected String fareSavingsTest;
    @XmlElement(name = "LastModifiedDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModifiedDate;
    @XmlElement(name = "OtherSavingsComparisonNotes", required = true)
    protected String otherSavingsComparisonNotes;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the savingsComparisonName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSavingsComparisonName() {
        return savingsComparisonName;
    }

    /**
     * Sets the value of the savingsComparisonName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSavingsComparisonName(String value) {
        this.savingsComparisonName = value;
    }

    /**
     * Gets the value of the otherSavingsComparisonName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherSavingsComparisonName() {
        return otherSavingsComparisonName;
    }

    /**
     * Sets the value of the otherSavingsComparisonName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherSavingsComparisonName(String value) {
        this.otherSavingsComparisonName = value;
    }

    /**
     * Gets the value of the countries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountries() {
        return countries;
    }

    /**
     * Sets the value of the countries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountries(String value) {
        this.countries = value;
    }

    /**
     * Gets the value of the savingsComparisonType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSavingsComparisonType() {
        return savingsComparisonType;
    }

    /**
     * Sets the value of the savingsComparisonType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSavingsComparisonType(String value) {
        this.savingsComparisonType = value;
    }

    /**
     * Gets the value of the otherSavingsComparisionSourceofData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherSavingsComparisionSourceofData() {
        return otherSavingsComparisionSourceofData;
    }

    /**
     * Sets the value of the otherSavingsComparisionSourceofData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherSavingsComparisionSourceofData(String value) {
        this.otherSavingsComparisionSourceofData = value;
    }

    /**
     * Gets the value of the otherSavingsComparisonRequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherSavingsComparisonRequired() {
        return otherSavingsComparisonRequired;
    }

    /**
     * Sets the value of the otherSavingsComparisonRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherSavingsComparisonRequired(String value) {
        this.otherSavingsComparisonRequired = value;
    }

    /**
     * Gets the value of the otherSavingComparisonDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherSavingComparisonDefinition() {
        return otherSavingComparisonDefinition;
    }

    /**
     * Sets the value of the otherSavingComparisonDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherSavingComparisonDefinition(String value) {
        this.otherSavingComparisonDefinition = value;
    }

    /**
     * Gets the value of the otherSavingComparisionadditionalnote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherSavingComparisionadditionalnote() {
        return otherSavingComparisionadditionalnote;
    }

    /**
     * Sets the value of the otherSavingComparisionadditionalnote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherSavingComparisionadditionalnote(String value) {
        this.otherSavingComparisionadditionalnote = value;
    }

    /**
     * Gets the value of the fareSavingsTest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFareSavingsTest() {
        return fareSavingsTest;
    }

    /**
     * Sets the value of the fareSavingsTest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFareSavingsTest(String value) {
        this.fareSavingsTest = value;
    }

    /**
     * Gets the value of the lastModifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * Sets the value of the lastModifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModifiedDate(XMLGregorianCalendar value) {
        this.lastModifiedDate = value;
    }

    /**
     * Gets the value of the otherSavingsComparisonNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherSavingsComparisonNotes() {
        return otherSavingsComparisonNotes;
    }

    /**
     * Sets the value of the otherSavingsComparisonNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherSavingsComparisonNotes(String value) {
        this.otherSavingsComparisonNotes = value;
    }

}
