//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.22 at 01:33:26 AM SGT 
//


package com.bcd.bdu.model.accounts;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ReasonCodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReasonCodeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReasonCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReasonCodeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReasonCodeType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GlobalBCDDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BCDCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GEMSCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GROCodec" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MAXCodec" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LowFareComparedtoFarePaid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OtherGlobalBCDDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OtherBCD_Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OtherGEMSCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Other" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OtherMAXCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReasonCodesNotes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LastModifiedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReasonCodeType", propOrder = {
    "reasonCode",
    "reasonCodeName",
    "reasonCodeType",
    "globalBCDDescription",
    "bcdCode",
    "gemsCode",
    "groCodec",
    "maxCodec",
    "lowFareComparedtoFarePaid",
    "otherGlobalBCDDescription",
    "otherBCDCode",
    "otherGEMSCode",
    "other",
    "otherMAXCode",
    "reasonCodesNotes",
    "lastModifiedDate"
})
public class ReasonCodeType {

    @XmlElement(name = "ReasonCode", required = true)
    protected String reasonCode;
    @XmlElement(name = "ReasonCodeName", required = true)
    protected String reasonCodeName;
    @XmlElement(name = "ReasonCodeType", required = true)
    protected String reasonCodeType;
    @XmlElement(name = "GlobalBCDDescription", required = true)
    protected String globalBCDDescription;
    @XmlElement(name = "BCDCode", required = true)
    protected String bcdCode;
    @XmlElement(name = "GEMSCode", required = true)
    protected String gemsCode;
    @XmlElement(name = "GROCodec", required = true)
    protected String groCodec;
    @XmlElement(name = "MAXCodec", required = true)
    protected String maxCodec;
    @XmlElement(name = "LowFareComparedtoFarePaid")
    protected String lowFareComparedtoFarePaid;
    @XmlElement(name = "OtherGlobalBCDDescription")
    protected String otherGlobalBCDDescription;
    @XmlElement(name = "OtherBCD_Code")
    protected String otherBCDCode;
    @XmlElement(name = "OtherGEMSCode")
    protected String otherGEMSCode;
    @XmlElement(name = "Other")
    protected String other;
    @XmlElement(name = "OtherMAXCode")
    protected String otherMAXCode;
    @XmlElement(name = "ReasonCodesNotes")
    protected String reasonCodesNotes;
    @XmlElement(name = "LastModifiedDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModifiedDate;

    /**
     * Gets the value of the reasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCode() {
        return reasonCode;
    }

    /**
     * Sets the value of the reasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonCode(String value) {
        this.reasonCode = value;
    }

    /**
     * Gets the value of the reasonCodeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCodeName() {
        return reasonCodeName;
    }

    /**
     * Sets the value of the reasonCodeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonCodeName(String value) {
        this.reasonCodeName = value;
    }

    /**
     * Gets the value of the reasonCodeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCodeType() {
        return reasonCodeType;
    }

    /**
     * Sets the value of the reasonCodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonCodeType(String value) {
        this.reasonCodeType = value;
    }

    /**
     * Gets the value of the globalBCDDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalBCDDescription() {
        return globalBCDDescription;
    }

    /**
     * Sets the value of the globalBCDDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalBCDDescription(String value) {
        this.globalBCDDescription = value;
    }

    /**
     * Gets the value of the bcdCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBCDCode() {
        return bcdCode;
    }

    /**
     * Sets the value of the bcdCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBCDCode(String value) {
        this.bcdCode = value;
    }

    /**
     * Gets the value of the gemsCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGEMSCode() {
        return gemsCode;
    }

    /**
     * Sets the value of the gemsCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGEMSCode(String value) {
        this.gemsCode = value;
    }

    /**
     * Gets the value of the groCodec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGROCodec() {
        return groCodec;
    }

    /**
     * Sets the value of the groCodec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGROCodec(String value) {
        this.groCodec = value;
    }

    /**
     * Gets the value of the maxCodec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAXCodec() {
        return maxCodec;
    }

    /**
     * Sets the value of the maxCodec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAXCodec(String value) {
        this.maxCodec = value;
    }

    /**
     * Gets the value of the lowFareComparedtoFarePaid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLowFareComparedtoFarePaid() {
        return lowFareComparedtoFarePaid;
    }

    /**
     * Sets the value of the lowFareComparedtoFarePaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLowFareComparedtoFarePaid(String value) {
        this.lowFareComparedtoFarePaid = value;
    }

    /**
     * Gets the value of the otherGlobalBCDDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherGlobalBCDDescription() {
        return otherGlobalBCDDescription;
    }

    /**
     * Sets the value of the otherGlobalBCDDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherGlobalBCDDescription(String value) {
        this.otherGlobalBCDDescription = value;
    }

    /**
     * Gets the value of the otherBCDCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherBCDCode() {
        return otherBCDCode;
    }

    /**
     * Sets the value of the otherBCDCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherBCDCode(String value) {
        this.otherBCDCode = value;
    }

    /**
     * Gets the value of the otherGEMSCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherGEMSCode() {
        return otherGEMSCode;
    }

    /**
     * Sets the value of the otherGEMSCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherGEMSCode(String value) {
        this.otherGEMSCode = value;
    }

    /**
     * Gets the value of the other property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOther() {
        return other;
    }

    /**
     * Sets the value of the other property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOther(String value) {
        this.other = value;
    }

    /**
     * Gets the value of the otherMAXCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherMAXCode() {
        return otherMAXCode;
    }

    /**
     * Sets the value of the otherMAXCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherMAXCode(String value) {
        this.otherMAXCode = value;
    }

    /**
     * Gets the value of the reasonCodesNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCodesNotes() {
        return reasonCodesNotes;
    }

    /**
     * Sets the value of the reasonCodesNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonCodesNotes(String value) {
        this.reasonCodesNotes = value;
    }

    /**
     * Gets the value of the lastModifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * Sets the value of the lastModifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModifiedDate(XMLGregorianCalendar value) {
        this.lastModifiedDate = value;
    }

}
