//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.22 at 01:33:26 AM SGT 
//


package com.bcd.bdu.model.accounts;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ReportingRemarkType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReportingRemarkType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RemarkLabel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RemarksOthers" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MAX" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GRO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GEMS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GDS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GDSPrefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DataType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GDSSecondary" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GDSPrefixSecondary" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RemarkType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LastModifiedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="RemarkExample" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RemarkExampleSecondary" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Required" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MinLength" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MaxLength" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NotesSecondary" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Lookups" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Lookup" type="{}LookupType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReportingRemarkType", propOrder = {
    "remarkLabel",
    "remarksOthers",
    "max",
    "gro",
    "gems",
    "gds",
    "gdsPrefix",
    "dataType",
    "gdsSecondary",
    "gdsPrefixSecondary",
    "remarkType",
    "lastModifiedDate",
    "remarkExample",
    "remarkExampleSecondary",
    "required",
    "minLength",
    "maxLength",
    "notes",
    "notesSecondary",
    "lookups"
})
public class ReportingRemarkType {

    @XmlElement(name = "RemarkLabel", required = true)
    protected String remarkLabel;
    @XmlElement(name = "RemarksOthers", required = true)
    protected String remarksOthers;
    @XmlElement(name = "MAX", required = true)
    protected String max;
    @XmlElement(name = "GRO", required = true)
    protected String gro;
    @XmlElement(name = "GEMS", required = true)
    protected String gems;
    @XmlElement(name = "GDS", required = true)
    protected String gds;
    @XmlElement(name = "GDSPrefix", required = true)
    protected String gdsPrefix;
    @XmlElement(name = "DataType", required = true)
    protected String dataType;
    @XmlElement(name = "GDSSecondary", required = true)
    protected String gdsSecondary;
    @XmlElement(name = "GDSPrefixSecondary", required = true)
    protected String gdsPrefixSecondary;
    @XmlElement(name = "RemarkType", required = true)
    protected String remarkType;
    @XmlElement(name = "LastModifiedDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModifiedDate;
    @XmlElement(name = "RemarkExample", required = true)
    protected String remarkExample;
    @XmlElement(name = "RemarkExampleSecondary", required = true)
    protected String remarkExampleSecondary;
    @XmlElement(name = "Required", required = true)
    protected String required;
    @XmlElement(name = "MinLength", required = true)
    protected String minLength;
    @XmlElement(name = "MaxLength", required = true)
    protected String maxLength;
    @XmlElement(name = "Notes", required = true)
    protected String notes;
    @XmlElement(name = "NotesSecondary", required = true)
    protected String notesSecondary;
    @XmlElement(name = "Lookups")
    protected ReportingRemarkType.Lookups lookups;

    /**
     * Gets the value of the remarkLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarkLabel() {
        return remarkLabel;
    }

    /**
     * Sets the value of the remarkLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarkLabel(String value) {
        this.remarkLabel = value;
    }

    /**
     * Gets the value of the remarksOthers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarksOthers() {
        return remarksOthers;
    }

    /**
     * Sets the value of the remarksOthers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarksOthers(String value) {
        this.remarksOthers = value;
    }

    /**
     * Gets the value of the max property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAX() {
        return max;
    }

    /**
     * Sets the value of the max property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAX(String value) {
        this.max = value;
    }

    /**
     * Gets the value of the gro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGRO() {
        return gro;
    }

    /**
     * Sets the value of the gro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGRO(String value) {
        this.gro = value;
    }

    /**
     * Gets the value of the gems property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGEMS() {
        return gems;
    }

    /**
     * Sets the value of the gems property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGEMS(String value) {
        this.gems = value;
    }

    /**
     * Gets the value of the gds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGDS() {
        return gds;
    }

    /**
     * Sets the value of the gds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGDS(String value) {
        this.gds = value;
    }

    /**
     * Gets the value of the gdsPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGDSPrefix() {
        return gdsPrefix;
    }

    /**
     * Sets the value of the gdsPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGDSPrefix(String value) {
        this.gdsPrefix = value;
    }

    /**
     * Gets the value of the dataType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataType(String value) {
        this.dataType = value;
    }

    /**
     * Gets the value of the gdsSecondary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGDSSecondary() {
        return gdsSecondary;
    }

    /**
     * Sets the value of the gdsSecondary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGDSSecondary(String value) {
        this.gdsSecondary = value;
    }

    /**
     * Gets the value of the gdsPrefixSecondary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGDSPrefixSecondary() {
        return gdsPrefixSecondary;
    }

    /**
     * Sets the value of the gdsPrefixSecondary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGDSPrefixSecondary(String value) {
        this.gdsPrefixSecondary = value;
    }

    /**
     * Gets the value of the remarkType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarkType() {
        return remarkType;
    }

    /**
     * Sets the value of the remarkType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarkType(String value) {
        this.remarkType = value;
    }

    /**
     * Gets the value of the lastModifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * Sets the value of the lastModifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModifiedDate(XMLGregorianCalendar value) {
        this.lastModifiedDate = value;
    }

    /**
     * Gets the value of the remarkExample property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarkExample() {
        return remarkExample;
    }

    /**
     * Sets the value of the remarkExample property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarkExample(String value) {
        this.remarkExample = value;
    }

    /**
     * Gets the value of the remarkExampleSecondary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarkExampleSecondary() {
        return remarkExampleSecondary;
    }

    /**
     * Sets the value of the remarkExampleSecondary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarkExampleSecondary(String value) {
        this.remarkExampleSecondary = value;
    }

    /**
     * Gets the value of the required property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequired(String value) {
        this.required = value;
    }

    /**
     * Gets the value of the minLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinLength() {
        return minLength;
    }

    /**
     * Sets the value of the minLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinLength(String value) {
        this.minLength = value;
    }

    /**
     * Gets the value of the maxLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxLength() {
        return maxLength;
    }

    /**
     * Sets the value of the maxLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxLength(String value) {
        this.maxLength = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the notesSecondary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotesSecondary() {
        return notesSecondary;
    }

    /**
     * Sets the value of the notesSecondary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotesSecondary(String value) {
        this.notesSecondary = value;
    }

    /**
     * Gets the value of the lookups property.
     * 
     * @return
     *     possible object is
     *     {@link ReportingRemarkType.Lookups }
     *     
     */
    public ReportingRemarkType.Lookups getLookups() {
        return lookups;
    }

    /**
     * Sets the value of the lookups property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportingRemarkType.Lookups }
     *     
     */
    public void setLookups(ReportingRemarkType.Lookups value) {
        this.lookups = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Lookup" type="{}LookupType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lookup"
    })
    public static class Lookups {

        @XmlElement(name = "Lookup")
        protected List<LookupType> lookup;

        /**
         * Gets the value of the lookup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the lookup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLookup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LookupType }
         * 
         * 
         */
        public List<LookupType> getLookup() {
            if (lookup == null) {
                lookup = new ArrayList<LookupType>();
            }
            return this.lookup;
        }

    }

}
