//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.22 at 01:33:26 AM SGT 
//


package com.bcd.bdu.model.accounts;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SavingsComparisonType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SavingsComparisonType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SavingsComparisonType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LastModifiedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="GlobalAirSavingsComparison">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element name="LowFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="LowFareDefinition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="LowFareDefinitionifOther" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="NotesLowFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ReferenceFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ReferenceFareDefinition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ReferenceFareDefinitionifOther" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="NotesReferenceFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="GlobalAuxiliarySavingsComparison">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element name="HotelStandardRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CarStandardRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HotelStandardRateifOther" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="LowFareSavings">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="LowFareDefinitionL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="USCASourceofDatalowfaresavings" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="LowFareSavingsTest" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="USCANotesLowFareSavings" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="USCARequiredlowfaresavings" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="USCAadditionalnotesLowFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ReferenceFare">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="NormalFareDefinition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="USCASourceofDataRefer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="LowFareSavingsTestReferenceFare" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="USCANotesReferenceFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="USCARequiredReferenceFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="USCAadditionalnotesReferenceFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DollarSavings">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DollarSavingsDefinition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="USCASourceofDataDollarSavings" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="LowFareSavingsTestDollarSavings" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="USCANotesDollarSavings" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="USCARequiredDollarSavings" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="USCAadditionalnotesDollarSavings" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AuxiliarySavingsComparison">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element name="USCAHotelStandardRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="USCAStandardRateDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="USCACarStandardRate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="USCACarStandardRateDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OtherSavingsComparisons" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="OtherSavingsComparison" type="{}OtherSavingsComparisonType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SavingsComparisonType", propOrder = {
    "savingsComparisonType",
    "name",
    "lastModifiedDate",
    "globalAirSavingsComparison",
    "globalAuxiliarySavingsComparison",
    "lowFareSavings",
    "referenceFare",
    "dollarSavings",
    "auxiliarySavingsComparison",
    "otherSavingsComparisons"
})
public class SavingsComparisonType {

    @XmlElement(name = "SavingsComparisonType", required = true)
    protected String savingsComparisonType;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "LastModifiedDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModifiedDate;
    @XmlElement(name = "GlobalAirSavingsComparison", required = true)
    protected SavingsComparisonType.GlobalAirSavingsComparison globalAirSavingsComparison;
    @XmlElement(name = "GlobalAuxiliarySavingsComparison", required = true)
    protected SavingsComparisonType.GlobalAuxiliarySavingsComparison globalAuxiliarySavingsComparison;
    @XmlElement(name = "LowFareSavings", required = true)
    protected SavingsComparisonType.LowFareSavings lowFareSavings;
    @XmlElement(name = "ReferenceFare", required = true)
    protected SavingsComparisonType.ReferenceFare referenceFare;
    @XmlElement(name = "DollarSavings", required = true)
    protected SavingsComparisonType.DollarSavings dollarSavings;
    @XmlElement(name = "AuxiliarySavingsComparison", required = true)
    protected SavingsComparisonType.AuxiliarySavingsComparison auxiliarySavingsComparison;
    @XmlElement(name = "OtherSavingsComparisons")
    protected SavingsComparisonType.OtherSavingsComparisons otherSavingsComparisons;

    /**
     * Gets the value of the savingsComparisonType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSavingsComparisonType() {
        return savingsComparisonType;
    }

    /**
     * Sets the value of the savingsComparisonType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSavingsComparisonType(String value) {
        this.savingsComparisonType = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the lastModifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * Sets the value of the lastModifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModifiedDate(XMLGregorianCalendar value) {
        this.lastModifiedDate = value;
    }

    /**
     * Gets the value of the globalAirSavingsComparison property.
     * 
     * @return
     *     possible object is
     *     {@link SavingsComparisonType.GlobalAirSavingsComparison }
     *     
     */
    public SavingsComparisonType.GlobalAirSavingsComparison getGlobalAirSavingsComparison() {
        return globalAirSavingsComparison;
    }

    /**
     * Sets the value of the globalAirSavingsComparison property.
     * 
     * @param value
     *     allowed object is
     *     {@link SavingsComparisonType.GlobalAirSavingsComparison }
     *     
     */
    public void setGlobalAirSavingsComparison(SavingsComparisonType.GlobalAirSavingsComparison value) {
        this.globalAirSavingsComparison = value;
    }

    /**
     * Gets the value of the globalAuxiliarySavingsComparison property.
     * 
     * @return
     *     possible object is
     *     {@link SavingsComparisonType.GlobalAuxiliarySavingsComparison }
     *     
     */
    public SavingsComparisonType.GlobalAuxiliarySavingsComparison getGlobalAuxiliarySavingsComparison() {
        return globalAuxiliarySavingsComparison;
    }

    /**
     * Sets the value of the globalAuxiliarySavingsComparison property.
     * 
     * @param value
     *     allowed object is
     *     {@link SavingsComparisonType.GlobalAuxiliarySavingsComparison }
     *     
     */
    public void setGlobalAuxiliarySavingsComparison(SavingsComparisonType.GlobalAuxiliarySavingsComparison value) {
        this.globalAuxiliarySavingsComparison = value;
    }

    /**
     * Gets the value of the lowFareSavings property.
     * 
     * @return
     *     possible object is
     *     {@link SavingsComparisonType.LowFareSavings }
     *     
     */
    public SavingsComparisonType.LowFareSavings getLowFareSavings() {
        return lowFareSavings;
    }

    /**
     * Sets the value of the lowFareSavings property.
     * 
     * @param value
     *     allowed object is
     *     {@link SavingsComparisonType.LowFareSavings }
     *     
     */
    public void setLowFareSavings(SavingsComparisonType.LowFareSavings value) {
        this.lowFareSavings = value;
    }

    /**
     * Gets the value of the referenceFare property.
     * 
     * @return
     *     possible object is
     *     {@link SavingsComparisonType.ReferenceFare }
     *     
     */
    public SavingsComparisonType.ReferenceFare getReferenceFare() {
        return referenceFare;
    }

    /**
     * Sets the value of the referenceFare property.
     * 
     * @param value
     *     allowed object is
     *     {@link SavingsComparisonType.ReferenceFare }
     *     
     */
    public void setReferenceFare(SavingsComparisonType.ReferenceFare value) {
        this.referenceFare = value;
    }

    /**
     * Gets the value of the dollarSavings property.
     * 
     * @return
     *     possible object is
     *     {@link SavingsComparisonType.DollarSavings }
     *     
     */
    public SavingsComparisonType.DollarSavings getDollarSavings() {
        return dollarSavings;
    }

    /**
     * Sets the value of the dollarSavings property.
     * 
     * @param value
     *     allowed object is
     *     {@link SavingsComparisonType.DollarSavings }
     *     
     */
    public void setDollarSavings(SavingsComparisonType.DollarSavings value) {
        this.dollarSavings = value;
    }

    /**
     * Gets the value of the auxiliarySavingsComparison property.
     * 
     * @return
     *     possible object is
     *     {@link SavingsComparisonType.AuxiliarySavingsComparison }
     *     
     */
    public SavingsComparisonType.AuxiliarySavingsComparison getAuxiliarySavingsComparison() {
        return auxiliarySavingsComparison;
    }

    /**
     * Sets the value of the auxiliarySavingsComparison property.
     * 
     * @param value
     *     allowed object is
     *     {@link SavingsComparisonType.AuxiliarySavingsComparison }
     *     
     */
    public void setAuxiliarySavingsComparison(SavingsComparisonType.AuxiliarySavingsComparison value) {
        this.auxiliarySavingsComparison = value;
    }

    /**
     * Gets the value of the otherSavingsComparisons property.
     * 
     * @return
     *     possible object is
     *     {@link SavingsComparisonType.OtherSavingsComparisons }
     *     
     */
    public SavingsComparisonType.OtherSavingsComparisons getOtherSavingsComparisons() {
        return otherSavingsComparisons;
    }

    /**
     * Sets the value of the otherSavingsComparisons property.
     * 
     * @param value
     *     allowed object is
     *     {@link SavingsComparisonType.OtherSavingsComparisons }
     *     
     */
    public void setOtherSavingsComparisons(SavingsComparisonType.OtherSavingsComparisons value) {
        this.otherSavingsComparisons = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence minOccurs="0">
     *         &lt;element name="USCAHotelStandardRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="USCAStandardRateDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="USCACarStandardRate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="USCACarStandardRateDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "uscaHotelStandardRate",
        "uscaStandardRateDescription",
        "uscaCarStandardRate",
        "uscaCarStandardRateDescription"
    })
    public static class AuxiliarySavingsComparison {

        @XmlElement(name = "USCAHotelStandardRate")
        protected String uscaHotelStandardRate;
        @XmlElement(name = "USCAStandardRateDescription")
        protected String uscaStandardRateDescription;
        @XmlElement(name = "USCACarStandardRate")
        protected String uscaCarStandardRate;
        @XmlElement(name = "USCACarStandardRateDescription")
        protected String uscaCarStandardRateDescription;

        /**
         * Gets the value of the uscaHotelStandardRate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSCAHotelStandardRate() {
            return uscaHotelStandardRate;
        }

        /**
         * Sets the value of the uscaHotelStandardRate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSCAHotelStandardRate(String value) {
            this.uscaHotelStandardRate = value;
        }

        /**
         * Gets the value of the uscaStandardRateDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSCAStandardRateDescription() {
            return uscaStandardRateDescription;
        }

        /**
         * Sets the value of the uscaStandardRateDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSCAStandardRateDescription(String value) {
            this.uscaStandardRateDescription = value;
        }

        /**
         * Gets the value of the uscaCarStandardRate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSCACarStandardRate() {
            return uscaCarStandardRate;
        }

        /**
         * Sets the value of the uscaCarStandardRate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSCACarStandardRate(String value) {
            this.uscaCarStandardRate = value;
        }

        /**
         * Gets the value of the uscaCarStandardRateDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSCACarStandardRateDescription() {
            return uscaCarStandardRateDescription;
        }

        /**
         * Sets the value of the uscaCarStandardRateDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSCACarStandardRateDescription(String value) {
            this.uscaCarStandardRateDescription = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DollarSavingsDefinition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="USCASourceofDataDollarSavings" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="LowFareSavingsTestDollarSavings" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="USCANotesDollarSavings" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="USCARequiredDollarSavings" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="USCAadditionalnotesDollarSavings" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dollarSavingsDefinition",
        "uscaSourceofDataDollarSavings",
        "lowFareSavingsTestDollarSavings",
        "uscaNotesDollarSavings",
        "uscaRequiredDollarSavings",
        "uscAadditionalnotesDollarSavings"
    })
    public static class DollarSavings {

        @XmlElement(name = "DollarSavingsDefinition")
        protected String dollarSavingsDefinition;
        @XmlElement(name = "USCASourceofDataDollarSavings")
        protected String uscaSourceofDataDollarSavings;
        @XmlElement(name = "LowFareSavingsTestDollarSavings", required = true)
        protected String lowFareSavingsTestDollarSavings;
        @XmlElement(name = "USCANotesDollarSavings")
        protected String uscaNotesDollarSavings;
        @XmlElement(name = "USCARequiredDollarSavings", required = true)
        protected String uscaRequiredDollarSavings;
        @XmlElement(name = "USCAadditionalnotesDollarSavings")
        protected String uscAadditionalnotesDollarSavings;

        /**
         * Gets the value of the dollarSavingsDefinition property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDollarSavingsDefinition() {
            return dollarSavingsDefinition;
        }

        /**
         * Sets the value of the dollarSavingsDefinition property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDollarSavingsDefinition(String value) {
            this.dollarSavingsDefinition = value;
        }

        /**
         * Gets the value of the uscaSourceofDataDollarSavings property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSCASourceofDataDollarSavings() {
            return uscaSourceofDataDollarSavings;
        }

        /**
         * Sets the value of the uscaSourceofDataDollarSavings property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSCASourceofDataDollarSavings(String value) {
            this.uscaSourceofDataDollarSavings = value;
        }

        /**
         * Gets the value of the lowFareSavingsTestDollarSavings property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLowFareSavingsTestDollarSavings() {
            return lowFareSavingsTestDollarSavings;
        }

        /**
         * Sets the value of the lowFareSavingsTestDollarSavings property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLowFareSavingsTestDollarSavings(String value) {
            this.lowFareSavingsTestDollarSavings = value;
        }

        /**
         * Gets the value of the uscaNotesDollarSavings property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSCANotesDollarSavings() {
            return uscaNotesDollarSavings;
        }

        /**
         * Sets the value of the uscaNotesDollarSavings property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSCANotesDollarSavings(String value) {
            this.uscaNotesDollarSavings = value;
        }

        /**
         * Gets the value of the uscaRequiredDollarSavings property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSCARequiredDollarSavings() {
            return uscaRequiredDollarSavings;
        }

        /**
         * Sets the value of the uscaRequiredDollarSavings property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSCARequiredDollarSavings(String value) {
            this.uscaRequiredDollarSavings = value;
        }

        /**
         * Gets the value of the uscAadditionalnotesDollarSavings property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSCAadditionalnotesDollarSavings() {
            return uscAadditionalnotesDollarSavings;
        }

        /**
         * Sets the value of the uscAadditionalnotesDollarSavings property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSCAadditionalnotesDollarSavings(String value) {
            this.uscAadditionalnotesDollarSavings = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence minOccurs="0">
     *         &lt;element name="LowFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="LowFareDefinition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="LowFareDefinitionifOther" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="NotesLowFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ReferenceFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ReferenceFareDefinition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ReferenceFareDefinitionifOther" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="NotesReferenceFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lowFare",
        "lowFareDefinition",
        "lowFareDefinitionifOther",
        "notesLowFare",
        "referenceFare",
        "referenceFareDefinition",
        "referenceFareDefinitionifOther",
        "notesReferenceFare"
    })
    public static class GlobalAirSavingsComparison {

        @XmlElement(name = "LowFare")
        protected String lowFare;
        @XmlElement(name = "LowFareDefinition")
        protected String lowFareDefinition;
        @XmlElement(name = "LowFareDefinitionifOther")
        protected String lowFareDefinitionifOther;
        @XmlElement(name = "NotesLowFare")
        protected String notesLowFare;
        @XmlElement(name = "ReferenceFare")
        protected String referenceFare;
        @XmlElement(name = "ReferenceFareDefinition")
        protected String referenceFareDefinition;
        @XmlElement(name = "ReferenceFareDefinitionifOther")
        protected String referenceFareDefinitionifOther;
        @XmlElement(name = "NotesReferenceFare")
        protected String notesReferenceFare;

        /**
         * Gets the value of the lowFare property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLowFare() {
            return lowFare;
        }

        /**
         * Sets the value of the lowFare property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLowFare(String value) {
            this.lowFare = value;
        }

        /**
         * Gets the value of the lowFareDefinition property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLowFareDefinition() {
            return lowFareDefinition;
        }

        /**
         * Sets the value of the lowFareDefinition property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLowFareDefinition(String value) {
            this.lowFareDefinition = value;
        }

        /**
         * Gets the value of the lowFareDefinitionifOther property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLowFareDefinitionifOther() {
            return lowFareDefinitionifOther;
        }

        /**
         * Sets the value of the lowFareDefinitionifOther property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLowFareDefinitionifOther(String value) {
            this.lowFareDefinitionifOther = value;
        }

        /**
         * Gets the value of the notesLowFare property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotesLowFare() {
            return notesLowFare;
        }

        /**
         * Sets the value of the notesLowFare property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotesLowFare(String value) {
            this.notesLowFare = value;
        }

        /**
         * Gets the value of the referenceFare property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReferenceFare() {
            return referenceFare;
        }

        /**
         * Sets the value of the referenceFare property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReferenceFare(String value) {
            this.referenceFare = value;
        }

        /**
         * Gets the value of the referenceFareDefinition property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReferenceFareDefinition() {
            return referenceFareDefinition;
        }

        /**
         * Sets the value of the referenceFareDefinition property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReferenceFareDefinition(String value) {
            this.referenceFareDefinition = value;
        }

        /**
         * Gets the value of the referenceFareDefinitionifOther property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReferenceFareDefinitionifOther() {
            return referenceFareDefinitionifOther;
        }

        /**
         * Sets the value of the referenceFareDefinitionifOther property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReferenceFareDefinitionifOther(String value) {
            this.referenceFareDefinitionifOther = value;
        }

        /**
         * Gets the value of the notesReferenceFare property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotesReferenceFare() {
            return notesReferenceFare;
        }

        /**
         * Sets the value of the notesReferenceFare property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotesReferenceFare(String value) {
            this.notesReferenceFare = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence minOccurs="0">
     *         &lt;element name="HotelStandardRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CarStandardRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HotelStandardRateifOther" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hotelStandardRate",
        "carStandardRate",
        "hotelStandardRateifOther"
    })
    public static class GlobalAuxiliarySavingsComparison {

        @XmlElement(name = "HotelStandardRate")
        protected String hotelStandardRate;
        @XmlElement(name = "CarStandardRate")
        protected String carStandardRate;
        @XmlElement(name = "HotelStandardRateifOther")
        protected String hotelStandardRateifOther;

        /**
         * Gets the value of the hotelStandardRate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHotelStandardRate() {
            return hotelStandardRate;
        }

        /**
         * Sets the value of the hotelStandardRate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHotelStandardRate(String value) {
            this.hotelStandardRate = value;
        }

        /**
         * Gets the value of the carStandardRate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCarStandardRate() {
            return carStandardRate;
        }

        /**
         * Sets the value of the carStandardRate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCarStandardRate(String value) {
            this.carStandardRate = value;
        }

        /**
         * Gets the value of the hotelStandardRateifOther property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHotelStandardRateifOther() {
            return hotelStandardRateifOther;
        }

        /**
         * Sets the value of the hotelStandardRateifOther property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHotelStandardRateifOther(String value) {
            this.hotelStandardRateifOther = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="LowFareDefinitionL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="USCASourceofDatalowfaresavings" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="LowFareSavingsTest" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="USCANotesLowFareSavings" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="USCARequiredlowfaresavings" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="USCAadditionalnotesLowFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lowFareDefinitionL",
        "uscaSourceofDatalowfaresavings",
        "lowFareSavingsTest",
        "uscaNotesLowFareSavings",
        "uscaRequiredlowfaresavings",
        "uscAadditionalnotesLowFare"
    })
    public static class LowFareSavings {

        @XmlElement(name = "LowFareDefinitionL")
        protected String lowFareDefinitionL;
        @XmlElement(name = "USCASourceofDatalowfaresavings", required = true)
        protected String uscaSourceofDatalowfaresavings;
        @XmlElement(name = "LowFareSavingsTest")
        protected String lowFareSavingsTest;
        @XmlElement(name = "USCANotesLowFareSavings")
        protected String uscaNotesLowFareSavings;
        @XmlElement(name = "USCARequiredlowfaresavings")
        protected String uscaRequiredlowfaresavings;
        @XmlElement(name = "USCAadditionalnotesLowFare")
        protected String uscAadditionalnotesLowFare;

        /**
         * Gets the value of the lowFareDefinitionL property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLowFareDefinitionL() {
            return lowFareDefinitionL;
        }

        /**
         * Sets the value of the lowFareDefinitionL property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLowFareDefinitionL(String value) {
            this.lowFareDefinitionL = value;
        }

        /**
         * Gets the value of the uscaSourceofDatalowfaresavings property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSCASourceofDatalowfaresavings() {
            return uscaSourceofDatalowfaresavings;
        }

        /**
         * Sets the value of the uscaSourceofDatalowfaresavings property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSCASourceofDatalowfaresavings(String value) {
            this.uscaSourceofDatalowfaresavings = value;
        }

        /**
         * Gets the value of the lowFareSavingsTest property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLowFareSavingsTest() {
            return lowFareSavingsTest;
        }

        /**
         * Sets the value of the lowFareSavingsTest property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLowFareSavingsTest(String value) {
            this.lowFareSavingsTest = value;
        }

        /**
         * Gets the value of the uscaNotesLowFareSavings property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSCANotesLowFareSavings() {
            return uscaNotesLowFareSavings;
        }

        /**
         * Sets the value of the uscaNotesLowFareSavings property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSCANotesLowFareSavings(String value) {
            this.uscaNotesLowFareSavings = value;
        }

        /**
         * Gets the value of the uscaRequiredlowfaresavings property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSCARequiredlowfaresavings() {
            return uscaRequiredlowfaresavings;
        }

        /**
         * Sets the value of the uscaRequiredlowfaresavings property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSCARequiredlowfaresavings(String value) {
            this.uscaRequiredlowfaresavings = value;
        }

        /**
         * Gets the value of the uscAadditionalnotesLowFare property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSCAadditionalnotesLowFare() {
            return uscAadditionalnotesLowFare;
        }

        /**
         * Sets the value of the uscAadditionalnotesLowFare property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSCAadditionalnotesLowFare(String value) {
            this.uscAadditionalnotesLowFare = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="OtherSavingsComparison" type="{}OtherSavingsComparisonType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "otherSavingsComparison"
    })
    public static class OtherSavingsComparisons {

        @XmlElement(name = "OtherSavingsComparison")
        protected List<OtherSavingsComparisonType> otherSavingsComparison;

        /**
         * Gets the value of the otherSavingsComparison property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the otherSavingsComparison property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOtherSavingsComparison().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OtherSavingsComparisonType }
         * 
         * 
         */
        public List<OtherSavingsComparisonType> getOtherSavingsComparison() {
            if (otherSavingsComparison == null) {
                otherSavingsComparison = new ArrayList<OtherSavingsComparisonType>();
            }
            return this.otherSavingsComparison;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="NormalFareDefinition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="USCASourceofDataRefer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="LowFareSavingsTestReferenceFare" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="USCANotesReferenceFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="USCARequiredReferenceFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="USCAadditionalnotesReferenceFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "normalFareDefinition",
        "uscaSourceofDataRefer",
        "lowFareSavingsTestReferenceFare",
        "uscaNotesReferenceFare",
        "uscaRequiredReferenceFare",
        "uscAadditionalnotesReferenceFare"
    })
    public static class ReferenceFare {

        @XmlElement(name = "NormalFareDefinition")
        protected String normalFareDefinition;
        @XmlElement(name = "USCASourceofDataRefer")
        protected String uscaSourceofDataRefer;
        @XmlElement(name = "LowFareSavingsTestReferenceFare", required = true)
        protected String lowFareSavingsTestReferenceFare;
        @XmlElement(name = "USCANotesReferenceFare")
        protected String uscaNotesReferenceFare;
        @XmlElement(name = "USCARequiredReferenceFare")
        protected String uscaRequiredReferenceFare;
        @XmlElement(name = "USCAadditionalnotesReferenceFare")
        protected String uscAadditionalnotesReferenceFare;

        /**
         * Gets the value of the normalFareDefinition property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNormalFareDefinition() {
            return normalFareDefinition;
        }

        /**
         * Sets the value of the normalFareDefinition property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNormalFareDefinition(String value) {
            this.normalFareDefinition = value;
        }

        /**
         * Gets the value of the uscaSourceofDataRefer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSCASourceofDataRefer() {
            return uscaSourceofDataRefer;
        }

        /**
         * Sets the value of the uscaSourceofDataRefer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSCASourceofDataRefer(String value) {
            this.uscaSourceofDataRefer = value;
        }

        /**
         * Gets the value of the lowFareSavingsTestReferenceFare property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLowFareSavingsTestReferenceFare() {
            return lowFareSavingsTestReferenceFare;
        }

        /**
         * Sets the value of the lowFareSavingsTestReferenceFare property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLowFareSavingsTestReferenceFare(String value) {
            this.lowFareSavingsTestReferenceFare = value;
        }

        /**
         * Gets the value of the uscaNotesReferenceFare property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSCANotesReferenceFare() {
            return uscaNotesReferenceFare;
        }

        /**
         * Sets the value of the uscaNotesReferenceFare property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSCANotesReferenceFare(String value) {
            this.uscaNotesReferenceFare = value;
        }

        /**
         * Gets the value of the uscaRequiredReferenceFare property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSCARequiredReferenceFare() {
            return uscaRequiredReferenceFare;
        }

        /**
         * Sets the value of the uscaRequiredReferenceFare property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSCARequiredReferenceFare(String value) {
            this.uscaRequiredReferenceFare = value;
        }

        /**
         * Gets the value of the uscAadditionalnotesReferenceFare property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSCAadditionalnotesReferenceFare() {
            return uscAadditionalnotesReferenceFare;
        }

        /**
         * Sets the value of the uscAadditionalnotesReferenceFare property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSCAadditionalnotesReferenceFare(String value) {
            this.uscAadditionalnotesReferenceFare = value;
        }

    }

}
