//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.29 at 05:58:07 PM IST 
//


package com.bcd.bdu.api.response;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PNRInfo" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="pnrId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="accountId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="recordLocator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="emailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pnrInfo"
})
@XmlRootElement(name = "PNRList")
public class PNRList {

    @XmlElement(name = "PNRInfo")
    protected List<PNRList.PNRInfo> pnrInfo;

    /**
     * Gets the value of the pnrInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pnrInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPNRInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PNRList.PNRInfo }
     * 
     * 
     */
    public List<PNRList.PNRInfo> getPNRInfo() {
        if (pnrInfo == null) {
            pnrInfo = new ArrayList<PNRList.PNRInfo>();
        }
        return this.pnrInfo;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="pnrId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="accountId" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="recordLocator" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="emailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pnrId",
        "accountId",
        "recordLocator",
        "emailAddress"
    })
    public static class PNRInfo {

        @XmlElement(required = true)
        protected String pnrId;
        protected int accountId;
        @XmlElement(required = true)
        protected String recordLocator;
        @XmlElement(required = true)
        protected String emailAddress;

        /**
         * Gets the value of the pnrId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPnrId() {
            return pnrId;
        }

        /**
         * Sets the value of the pnrId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPnrId(String value) {
            this.pnrId = value;
        }

        /**
         * Gets the value of the accountId property.
         * 
         */
        public int getAccountId() {
            return accountId;
        }

        /**
         * Sets the value of the accountId property.
         * 
         */
        public void setAccountId(int value) {
            this.accountId = value;
        }

        /**
         * Gets the value of the recordLocator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordLocator() {
            return recordLocator;
        }

        /**
         * Sets the value of the recordLocator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordLocator(String value) {
            this.recordLocator = value;
        }

        /**
         * Gets the value of the emailAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmailAddress() {
            return emailAddress;
        }

        /**
         * Sets the value of the emailAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmailAddress(String value) {
            this.emailAddress = value;
        }

    }

}
