//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.02 at 10:16:47 AM IST 
//


package com.bcd.bdu.model.bookingdata.db;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Air complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Air">
 *   &lt;complexContent>
 *     &lt;extension base="{}Segment">
 *       &lt;sequence>
 *         &lt;element name="TicketInfo" type="{}TicketInfo" minOccurs="0"/>
 *         &lt;element name="bookingSiteConfNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Departure" type="{}AirportInfo" minOccurs="0"/>
 *         &lt;element name="Arrival" type="{}AirportInfo" minOccurs="0"/>
 *         &lt;element name="MarketingFlight" type="{}FlightInfo" minOccurs="0"/>
 *         &lt;element name="OperatingFlight" type="{}FlightInfo" minOccurs="0"/>
 *         &lt;element name="MealInfo" type="{}MealInfo" minOccurs="0"/>
 *         &lt;element name="equipmentCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClassOfService" type="{}ClassOfService" minOccurs="0"/>
 *         &lt;element name="Status" type="{}Status" minOccurs="0"/>
 *         &lt;element name="isChangeOfGuage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InFlightServiceCodes" type="{}InFlightServices" minOccurs="0"/>
 *         &lt;element name="calculatedDuration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numberOfStops" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flightDistance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StopCityList" type="{}StringList" minOccurs="0"/>
 *         &lt;element name="MarriedSegments" type="{}IntegerList" minOccurs="0"/>
 *         &lt;element name="ConnectedSegments" type="{}IntegerList" minOccurs="0"/>
 *         &lt;element name="isFlown" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isPassive" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="segmentRemarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="Air" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Air", propOrder = {
    "ticketInfo",
    "bookingSiteConfNum",
    "departure",
    "arrival",
    "marketingFlight",
    "operatingFlight",
    "mealInfo",
    "equipmentCode",
    "classOfService",
    "status",
    "isChangeOfGuage",
    "inFlightServiceCodes",
    "calculatedDuration",
    "numberOfStops",
    "flightDistance",
    "stopCityList",
    "marriedSegments",
    "connectedSegments",
    "isFlown",
    "isPassive",
    "segmentRemarks",
    "notes"
})
public class Air
    extends Segment
{

    @XmlElement(name = "TicketInfo")
    protected TicketInfo ticketInfo;
    protected String bookingSiteConfNum;
    @XmlElement(name = "Departure")
    protected AirportInfo departure;
    @XmlElement(name = "Arrival")
    protected AirportInfo arrival;
    @XmlElement(name = "MarketingFlight")
    protected FlightInfo marketingFlight;
    @XmlElement(name = "OperatingFlight")
    protected FlightInfo operatingFlight;
    @XmlElement(name = "MealInfo")
    protected MealInfo mealInfo;
    protected String equipmentCode;
    @XmlElement(name = "ClassOfService")
    protected ClassOfService classOfService;
    @XmlElement(name = "Status")
    protected Status status;
    protected String isChangeOfGuage;
    @XmlElement(name = "InFlightServiceCodes")
    protected String inFlightServiceCodes;
    protected String calculatedDuration;
    protected String numberOfStops;
    protected String flightDistance;
    @XmlElement(name = "StopCityList")
    protected StringList stopCityList;
    @XmlElement(name = "MarriedSegments")
    protected IntegerList marriedSegments;
    @XmlElement(name = "ConnectedSegments")
    protected IntegerList connectedSegments;
    protected String isFlown;
    protected String isPassive;
    protected String segmentRemarks;
    protected String notes;
    @XmlAttribute(name = "type", required = true)
    protected String type;

    /**
     * Gets the value of the ticketInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TicketInfo }
     *     
     */
    public TicketInfo getTicketInfo() {
        return ticketInfo;
    }

    /**
     * Sets the value of the ticketInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TicketInfo }
     *     
     */
    public void setTicketInfo(TicketInfo value) {
        this.ticketInfo = value;
    }

    /**
     * Gets the value of the bookingSiteConfNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingSiteConfNum() {
        return bookingSiteConfNum;
    }

    /**
     * Sets the value of the bookingSiteConfNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingSiteConfNum(String value) {
        this.bookingSiteConfNum = value;
    }

    /**
     * Gets the value of the departure property.
     * 
     * @return
     *     possible object is
     *     {@link AirportInfo }
     *     
     */
    public AirportInfo getDeparture() {
        return departure;
    }

    /**
     * Sets the value of the departure property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirportInfo }
     *     
     */
    public void setDeparture(AirportInfo value) {
        this.departure = value;
    }

    /**
     * Gets the value of the arrival property.
     * 
     * @return
     *     possible object is
     *     {@link AirportInfo }
     *     
     */
    public AirportInfo getArrival() {
        return arrival;
    }

    /**
     * Sets the value of the arrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirportInfo }
     *     
     */
    public void setArrival(AirportInfo value) {
        this.arrival = value;
    }

    /**
     * Gets the value of the marketingFlight property.
     * 
     * @return
     *     possible object is
     *     {@link FlightInfo }
     *     
     */
    public FlightInfo getMarketingFlight() {
        return marketingFlight;
    }

    /**
     * Sets the value of the marketingFlight property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightInfo }
     *     
     */
    public void setMarketingFlight(FlightInfo value) {
        this.marketingFlight = value;
    }

    /**
     * Gets the value of the operatingFlight property.
     * 
     * @return
     *     possible object is
     *     {@link FlightInfo }
     *     
     */
    public FlightInfo getOperatingFlight() {
        return operatingFlight;
    }

    /**
     * Sets the value of the operatingFlight property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightInfo }
     *     
     */
    public void setOperatingFlight(FlightInfo value) {
        this.operatingFlight = value;
    }

    /**
     * Gets the value of the mealInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MealInfo }
     *     
     */
    public MealInfo getMealInfo() {
        return mealInfo;
    }

    /**
     * Sets the value of the mealInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MealInfo }
     *     
     */
    public void setMealInfo(MealInfo value) {
        this.mealInfo = value;
    }

    /**
     * Gets the value of the equipmentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipmentCode() {
        return equipmentCode;
    }

    /**
     * Sets the value of the equipmentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipmentCode(String value) {
        this.equipmentCode = value;
    }

    /**
     * Gets the value of the classOfService property.
     * 
     * @return
     *     possible object is
     *     {@link ClassOfService }
     *     
     */
    public ClassOfService getClassOfService() {
        return classOfService;
    }

    /**
     * Sets the value of the classOfService property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassOfService }
     *     
     */
    public void setClassOfService(ClassOfService value) {
        this.classOfService = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the isChangeOfGuage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsChangeOfGuage() {
        return isChangeOfGuage;
    }

    /**
     * Sets the value of the isChangeOfGuage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsChangeOfGuage(String value) {
        this.isChangeOfGuage = value;
    }

    /**
     * Gets the value of the inFlightServiceCodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInFlightServiceCodes() {
        return inFlightServiceCodes;
    }

    /**
     * Sets the value of the inFlightServiceCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInFlightServiceCodes(String value) {
        this.inFlightServiceCodes = value;
    }

    /**
     * Gets the value of the calculatedDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalculatedDuration() {
        return calculatedDuration;
    }

    /**
     * Sets the value of the calculatedDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalculatedDuration(String value) {
        this.calculatedDuration = value;
    }

    /**
     * Gets the value of the numberOfStops property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfStops() {
        return numberOfStops;
    }

    /**
     * Sets the value of the numberOfStops property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfStops(String value) {
        this.numberOfStops = value;
    }

    /**
     * Gets the value of the flightDistance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightDistance() {
        return flightDistance;
    }

    /**
     * Sets the value of the flightDistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightDistance(String value) {
        this.flightDistance = value;
    }

    /**
     * Gets the value of the stopCityList property.
     * 
     * @return
     *     possible object is
     *     {@link StringList }
     *     
     */
    public StringList getStopCityList() {
        return stopCityList;
    }

    /**
     * Sets the value of the stopCityList property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringList }
     *     
     */
    public void setStopCityList(StringList value) {
        this.stopCityList = value;
    }

    /**
     * Gets the value of the marriedSegments property.
     * 
     * @return
     *     possible object is
     *     {@link IntegerList }
     *     
     */
    public IntegerList getMarriedSegments() {
        return marriedSegments;
    }

    /**
     * Sets the value of the marriedSegments property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegerList }
     *     
     */
    public void setMarriedSegments(IntegerList value) {
        this.marriedSegments = value;
    }

    /**
     * Gets the value of the connectedSegments property.
     * 
     * @return
     *     possible object is
     *     {@link IntegerList }
     *     
     */
    public IntegerList getConnectedSegments() {
        return connectedSegments;
    }

    /**
     * Sets the value of the connectedSegments property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegerList }
     *     
     */
    public void setConnectedSegments(IntegerList value) {
        this.connectedSegments = value;
    }

    /**
     * Gets the value of the isFlown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsFlown() {
        return isFlown;
    }

    /**
     * Sets the value of the isFlown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsFlown(String value) {
        this.isFlown = value;
    }

    /**
     * Gets the value of the isPassive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPassive() {
        return isPassive;
    }

    /**
     * Sets the value of the isPassive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPassive(String value) {
        this.isPassive = value;
    }

    /**
     * Gets the value of the segmentRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegmentRemarks() {
        return segmentRemarks;
    }

    /**
     * Sets the value of the segmentRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegmentRemarks(String value) {
        this.segmentRemarks = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        if (type == null) {
            return "Air";
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
