//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.02 at 10:16:47 AM IST 
//


package com.bcd.bdu.model.bookingdata.db;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Car complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Car">
 *   &lt;complexContent>
 *     &lt;extension base="{}Segment">
 *       &lt;sequence>
 *         &lt;element name="bookingSiteConfNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bookingSiteURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bookingSource" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="supplierPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PickUp" type="{}AddressInfo" minOccurs="0"/>
 *         &lt;element name="DropOff" type="{}AddressInfo" minOccurs="0"/>
 *         &lt;element name="ArrivalFlight" type="{}FlightInfo" minOccurs="0"/>
 *         &lt;element name="Car" type="{}CarInfo" minOccurs="0"/>
 *         &lt;element name="rentalCompany" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Fare" type="{}CarFare" minOccurs="0"/>
 *         &lt;element name="serviceInformation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Status" type="{}Status" minOccurs="0"/>
 *         &lt;element name="frequentFlyerNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="frequentFlyerProgram" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reservationName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clientIDNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="guaranteeIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="corporateDiscountNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="frequentRenterID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="frequentRenterProgram" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isPassive" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="segmentRemarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Car", propOrder = {
    "bookingSiteConfNum",
    "bookingSiteURL",
    "bookingSource",
    "supplierPhone",
    "pickUp",
    "dropOff",
    "arrivalFlight",
    "car",
    "rentalCompany",
    "fare",
    "serviceInformation",
    "status",
    "frequentFlyerNumber",
    "frequentFlyerProgram",
    "reservationName",
    "clientIDNumber",
    "guaranteeIndicator",
    "corporateDiscountNumber",
    "frequentRenterID",
    "frequentRenterProgram",
    "isPassive",
    "segmentRemarks",
    "notes"
})
public class Car
    extends Segment
{

    protected String bookingSiteConfNum;
    protected String bookingSiteURL;
    protected String bookingSource;
    protected String supplierPhone;
    @XmlElement(name = "PickUp")
    protected AddressInfo pickUp;
    @XmlElement(name = "DropOff")
    protected AddressInfo dropOff;
    @XmlElement(name = "ArrivalFlight")
    protected FlightInfo arrivalFlight;
    @XmlElement(name = "Car")
    protected CarInfo car;
    protected String rentalCompany;
    @XmlElement(name = "Fare")
    protected CarFare fare;
    protected String serviceInformation;
    @XmlElement(name = "Status")
    protected Status status;
    protected String frequentFlyerNumber;
    protected String frequentFlyerProgram;
    protected String reservationName;
    protected String clientIDNumber;
    protected String guaranteeIndicator;
    protected String corporateDiscountNumber;
    protected String frequentRenterID;
    protected String frequentRenterProgram;
    protected String isPassive;
    protected String segmentRemarks;
    protected String notes;

    /**
     * Gets the value of the bookingSiteConfNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingSiteConfNum() {
        return bookingSiteConfNum;
    }

    /**
     * Sets the value of the bookingSiteConfNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingSiteConfNum(String value) {
        this.bookingSiteConfNum = value;
    }

    /**
     * Gets the value of the bookingSiteURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingSiteURL() {
        return bookingSiteURL;
    }

    /**
     * Sets the value of the bookingSiteURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingSiteURL(String value) {
        this.bookingSiteURL = value;
    }

    /**
     * Gets the value of the bookingSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingSource() {
        return bookingSource;
    }

    /**
     * Sets the value of the bookingSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingSource(String value) {
        this.bookingSource = value;
    }

    /**
     * Gets the value of the supplierPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierPhone() {
        return supplierPhone;
    }

    /**
     * Sets the value of the supplierPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierPhone(String value) {
        this.supplierPhone = value;
    }

    /**
     * Gets the value of the pickUp property.
     * 
     * @return
     *     possible object is
     *     {@link AddressInfo }
     *     
     */
    public AddressInfo getPickUp() {
        return pickUp;
    }

    /**
     * Sets the value of the pickUp property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressInfo }
     *     
     */
    public void setPickUp(AddressInfo value) {
        this.pickUp = value;
    }

    /**
     * Gets the value of the dropOff property.
     * 
     * @return
     *     possible object is
     *     {@link AddressInfo }
     *     
     */
    public AddressInfo getDropOff() {
        return dropOff;
    }

    /**
     * Sets the value of the dropOff property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressInfo }
     *     
     */
    public void setDropOff(AddressInfo value) {
        this.dropOff = value;
    }

    /**
     * Gets the value of the arrivalFlight property.
     * 
     * @return
     *     possible object is
     *     {@link FlightInfo }
     *     
     */
    public FlightInfo getArrivalFlight() {
        return arrivalFlight;
    }

    /**
     * Sets the value of the arrivalFlight property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightInfo }
     *     
     */
    public void setArrivalFlight(FlightInfo value) {
        this.arrivalFlight = value;
    }

    /**
     * Gets the value of the car property.
     * 
     * @return
     *     possible object is
     *     {@link CarInfo }
     *     
     */
    public CarInfo getCar() {
        return car;
    }

    /**
     * Sets the value of the car property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarInfo }
     *     
     */
    public void setCar(CarInfo value) {
        this.car = value;
    }

    /**
     * Gets the value of the rentalCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRentalCompany() {
        return rentalCompany;
    }

    /**
     * Sets the value of the rentalCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRentalCompany(String value) {
        this.rentalCompany = value;
    }

    /**
     * Gets the value of the fare property.
     * 
     * @return
     *     possible object is
     *     {@link CarFare }
     *     
     */
    public CarFare getFare() {
        return fare;
    }

    /**
     * Sets the value of the fare property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarFare }
     *     
     */
    public void setFare(CarFare value) {
        this.fare = value;
    }

    /**
     * Gets the value of the serviceInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceInformation() {
        return serviceInformation;
    }

    /**
     * Sets the value of the serviceInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceInformation(String value) {
        this.serviceInformation = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the frequentFlyerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequentFlyerNumber() {
        return frequentFlyerNumber;
    }

    /**
     * Sets the value of the frequentFlyerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequentFlyerNumber(String value) {
        this.frequentFlyerNumber = value;
    }

    /**
     * Gets the value of the frequentFlyerProgram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequentFlyerProgram() {
        return frequentFlyerProgram;
    }

    /**
     * Sets the value of the frequentFlyerProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequentFlyerProgram(String value) {
        this.frequentFlyerProgram = value;
    }

    /**
     * Gets the value of the reservationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReservationName() {
        return reservationName;
    }

    /**
     * Sets the value of the reservationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReservationName(String value) {
        this.reservationName = value;
    }

    /**
     * Gets the value of the clientIDNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientIDNumber() {
        return clientIDNumber;
    }

    /**
     * Sets the value of the clientIDNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientIDNumber(String value) {
        this.clientIDNumber = value;
    }

    /**
     * Gets the value of the guaranteeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuaranteeIndicator() {
        return guaranteeIndicator;
    }

    /**
     * Sets the value of the guaranteeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuaranteeIndicator(String value) {
        this.guaranteeIndicator = value;
    }

    /**
     * Gets the value of the corporateDiscountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorporateDiscountNumber() {
        return corporateDiscountNumber;
    }

    /**
     * Sets the value of the corporateDiscountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorporateDiscountNumber(String value) {
        this.corporateDiscountNumber = value;
    }

    /**
     * Gets the value of the frequentRenterID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequentRenterID() {
        return frequentRenterID;
    }

    /**
     * Sets the value of the frequentRenterID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequentRenterID(String value) {
        this.frequentRenterID = value;
    }

    /**
     * Gets the value of the frequentRenterProgram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequentRenterProgram() {
        return frequentRenterProgram;
    }

    /**
     * Sets the value of the frequentRenterProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequentRenterProgram(String value) {
        this.frequentRenterProgram = value;
    }

    /**
     * Gets the value of the isPassive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPassive() {
        return isPassive;
    }

    /**
     * Sets the value of the isPassive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPassive(String value) {
        this.isPassive = value;
    }

    /**
     * Gets the value of the segmentRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegmentRemarks() {
        return segmentRemarks;
    }

    /**
     * Sets the value of the segmentRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegmentRemarks(String value) {
        this.segmentRemarks = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

}
