//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.02 at 10:16:47 AM IST 
//


package com.bcd.bdu.model.bookingdata.db;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CarFare complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CarFare">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all minOccurs="0">
 *         &lt;element name="BaseRate" type="{}Fare"/>
 *         &lt;element name="rateCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GuaranteedRate" type="{}Fare"/>
 *         &lt;element name="EstimatedTotal" type="{}Fare"/>
 *         &lt;element name="QuotedRate" type="{}Fare"/>
 *         &lt;element name="DropCharge" type="{}Fare"/>
 *         &lt;element name="rateCurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dcsAuxRateCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OneWayDropFee" type="{}Fare"/>
 *         &lt;element name="rateCategory" type="{}RateCategories"/>
 *         &lt;element name="AgentEnteredRate" type="{}Fare"/>
 *         &lt;element name="CarRateType" type="{}RateType"/>
 *         &lt;element name="mileageAllowance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="extraDayMileageAllowance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ExtraDayFee" type="{}Fare"/>
 *         &lt;element name="ExtraHourFee" type="{}Fare"/>
 *         &lt;element name="MileCharge" type="{}Fare"/>
 *         &lt;element name="ExtraDayMileageFee" type="{}Fare"/>
 *         &lt;element name="extraHourMileageAllowance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ExtraHourMileageFee" type="{}Fare"/>
 *         &lt;element name="totalMandatoryCharges" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ExtraWeekFee" type="{}Fare"/>
 *         &lt;element name="ExtraWeekMileageFee" type="{}Fare"/>
 *         &lt;element name="extraWeekMileageAllowance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CarFare", propOrder = {

})
public class CarFare {

    @XmlElement(name = "BaseRate")
    protected Fare baseRate;
    protected String rateCode;
    @XmlElement(name = "GuaranteedRate")
    protected Fare guaranteedRate;
    @XmlElement(name = "EstimatedTotal")
    protected Fare estimatedTotal;
    @XmlElement(name = "QuotedRate")
    protected Fare quotedRate;
    @XmlElement(name = "DropCharge")
    protected Fare dropCharge;
    protected String rateCurrencyCode;
    protected String dcsAuxRateCode;
    @XmlElement(name = "OneWayDropFee")
    protected Fare oneWayDropFee;
    protected String rateCategory;
    @XmlElement(name = "AgentEnteredRate")
    protected Fare agentEnteredRate;
    @XmlElement(name = "CarRateType")
    protected String carRateType;
    protected String mileageAllowance;
    protected String extraDayMileageAllowance;
    @XmlElement(name = "ExtraDayFee")
    protected Fare extraDayFee;
    @XmlElement(name = "ExtraHourFee")
    protected Fare extraHourFee;
    @XmlElement(name = "MileCharge")
    protected Fare mileCharge;
    @XmlElement(name = "ExtraDayMileageFee")
    protected Fare extraDayMileageFee;
    protected String extraHourMileageAllowance;
    @XmlElement(name = "ExtraHourMileageFee")
    protected Fare extraHourMileageFee;
    protected String totalMandatoryCharges;
    @XmlElement(name = "ExtraWeekFee")
    protected Fare extraWeekFee;
    @XmlElement(name = "ExtraWeekMileageFee")
    protected Fare extraWeekMileageFee;
    protected String extraWeekMileageAllowance;

    /**
     * Gets the value of the baseRate property.
     * 
     * @return
     *     possible object is
     *     {@link Fare }
     *     
     */
    public Fare getBaseRate() {
        return baseRate;
    }

    /**
     * Sets the value of the baseRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fare }
     *     
     */
    public void setBaseRate(Fare value) {
        this.baseRate = value;
    }

    /**
     * Gets the value of the rateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateCode() {
        return rateCode;
    }

    /**
     * Sets the value of the rateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateCode(String value) {
        this.rateCode = value;
    }

    /**
     * Gets the value of the guaranteedRate property.
     * 
     * @return
     *     possible object is
     *     {@link Fare }
     *     
     */
    public Fare getGuaranteedRate() {
        return guaranteedRate;
    }

    /**
     * Sets the value of the guaranteedRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fare }
     *     
     */
    public void setGuaranteedRate(Fare value) {
        this.guaranteedRate = value;
    }

    /**
     * Gets the value of the estimatedTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Fare }
     *     
     */
    public Fare getEstimatedTotal() {
        return estimatedTotal;
    }

    /**
     * Sets the value of the estimatedTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fare }
     *     
     */
    public void setEstimatedTotal(Fare value) {
        this.estimatedTotal = value;
    }

    /**
     * Gets the value of the quotedRate property.
     * 
     * @return
     *     possible object is
     *     {@link Fare }
     *     
     */
    public Fare getQuotedRate() {
        return quotedRate;
    }

    /**
     * Sets the value of the quotedRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fare }
     *     
     */
    public void setQuotedRate(Fare value) {
        this.quotedRate = value;
    }

    /**
     * Gets the value of the dropCharge property.
     * 
     * @return
     *     possible object is
     *     {@link Fare }
     *     
     */
    public Fare getDropCharge() {
        return dropCharge;
    }

    /**
     * Sets the value of the dropCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fare }
     *     
     */
    public void setDropCharge(Fare value) {
        this.dropCharge = value;
    }

    /**
     * Gets the value of the rateCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateCurrencyCode() {
        return rateCurrencyCode;
    }

    /**
     * Sets the value of the rateCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateCurrencyCode(String value) {
        this.rateCurrencyCode = value;
    }

    /**
     * Gets the value of the dcsAuxRateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDcsAuxRateCode() {
        return dcsAuxRateCode;
    }

    /**
     * Sets the value of the dcsAuxRateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDcsAuxRateCode(String value) {
        this.dcsAuxRateCode = value;
    }

    /**
     * Gets the value of the oneWayDropFee property.
     * 
     * @return
     *     possible object is
     *     {@link Fare }
     *     
     */
    public Fare getOneWayDropFee() {
        return oneWayDropFee;
    }

    /**
     * Sets the value of the oneWayDropFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fare }
     *     
     */
    public void setOneWayDropFee(Fare value) {
        this.oneWayDropFee = value;
    }

    /**
     * Gets the value of the rateCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateCategory() {
        return rateCategory;
    }

    /**
     * Sets the value of the rateCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateCategory(String value) {
        this.rateCategory = value;
    }

    /**
     * Gets the value of the agentEnteredRate property.
     * 
     * @return
     *     possible object is
     *     {@link Fare }
     *     
     */
    public Fare getAgentEnteredRate() {
        return agentEnteredRate;
    }

    /**
     * Sets the value of the agentEnteredRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fare }
     *     
     */
    public void setAgentEnteredRate(Fare value) {
        this.agentEnteredRate = value;
    }

    /**
     * Gets the value of the carRateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarRateType() {
        return carRateType;
    }

    /**
     * Sets the value of the carRateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarRateType(String value) {
        this.carRateType = value;
    }

    /**
     * Gets the value of the mileageAllowance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMileageAllowance() {
        return mileageAllowance;
    }

    /**
     * Sets the value of the mileageAllowance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMileageAllowance(String value) {
        this.mileageAllowance = value;
    }

    /**
     * Gets the value of the extraDayMileageAllowance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtraDayMileageAllowance() {
        return extraDayMileageAllowance;
    }

    /**
     * Sets the value of the extraDayMileageAllowance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtraDayMileageAllowance(String value) {
        this.extraDayMileageAllowance = value;
    }

    /**
     * Gets the value of the extraDayFee property.
     * 
     * @return
     *     possible object is
     *     {@link Fare }
     *     
     */
    public Fare getExtraDayFee() {
        return extraDayFee;
    }

    /**
     * Sets the value of the extraDayFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fare }
     *     
     */
    public void setExtraDayFee(Fare value) {
        this.extraDayFee = value;
    }

    /**
     * Gets the value of the extraHourFee property.
     * 
     * @return
     *     possible object is
     *     {@link Fare }
     *     
     */
    public Fare getExtraHourFee() {
        return extraHourFee;
    }

    /**
     * Sets the value of the extraHourFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fare }
     *     
     */
    public void setExtraHourFee(Fare value) {
        this.extraHourFee = value;
    }

    /**
     * Gets the value of the mileCharge property.
     * 
     * @return
     *     possible object is
     *     {@link Fare }
     *     
     */
    public Fare getMileCharge() {
        return mileCharge;
    }

    /**
     * Sets the value of the mileCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fare }
     *     
     */
    public void setMileCharge(Fare value) {
        this.mileCharge = value;
    }

    /**
     * Gets the value of the extraDayMileageFee property.
     * 
     * @return
     *     possible object is
     *     {@link Fare }
     *     
     */
    public Fare getExtraDayMileageFee() {
        return extraDayMileageFee;
    }

    /**
     * Sets the value of the extraDayMileageFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fare }
     *     
     */
    public void setExtraDayMileageFee(Fare value) {
        this.extraDayMileageFee = value;
    }

    /**
     * Gets the value of the extraHourMileageAllowance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtraHourMileageAllowance() {
        return extraHourMileageAllowance;
    }

    /**
     * Sets the value of the extraHourMileageAllowance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtraHourMileageAllowance(String value) {
        this.extraHourMileageAllowance = value;
    }

    /**
     * Gets the value of the extraHourMileageFee property.
     * 
     * @return
     *     possible object is
     *     {@link Fare }
     *     
     */
    public Fare getExtraHourMileageFee() {
        return extraHourMileageFee;
    }

    /**
     * Sets the value of the extraHourMileageFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fare }
     *     
     */
    public void setExtraHourMileageFee(Fare value) {
        this.extraHourMileageFee = value;
    }

    /**
     * Gets the value of the totalMandatoryCharges property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalMandatoryCharges() {
        return totalMandatoryCharges;
    }

    /**
     * Sets the value of the totalMandatoryCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalMandatoryCharges(String value) {
        this.totalMandatoryCharges = value;
    }

    /**
     * Gets the value of the extraWeekFee property.
     * 
     * @return
     *     possible object is
     *     {@link Fare }
     *     
     */
    public Fare getExtraWeekFee() {
        return extraWeekFee;
    }

    /**
     * Sets the value of the extraWeekFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fare }
     *     
     */
    public void setExtraWeekFee(Fare value) {
        this.extraWeekFee = value;
    }

    /**
     * Gets the value of the extraWeekMileageFee property.
     * 
     * @return
     *     possible object is
     *     {@link Fare }
     *     
     */
    public Fare getExtraWeekMileageFee() {
        return extraWeekMileageFee;
    }

    /**
     * Sets the value of the extraWeekMileageFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fare }
     *     
     */
    public void setExtraWeekMileageFee(Fare value) {
        this.extraWeekMileageFee = value;
    }

    /**
     * Gets the value of the extraWeekMileageAllowance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtraWeekMileageAllowance() {
        return extraWeekMileageAllowance;
    }

    /**
     * Sets the value of the extraWeekMileageAllowance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtraWeekMileageAllowance(String value) {
        this.extraWeekMileageAllowance = value;
    }

}
