//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.02 at 10:16:47 AM IST 
//


package com.bcd.bdu.model.bookingdata.db;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Hotel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Hotel">
 *   &lt;complexContent>
 *     &lt;extension base="{}Segment">
 *       &lt;sequence>
 *         &lt;element name="bookingSiteConfNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bookingSiteURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bookingSource" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="supplierPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hotel" type="{}HotelInfo" minOccurs="0"/>
 *         &lt;element name="RoomInfo" type="{}RoomInfo" minOccurs="0"/>
 *         &lt;element name="Status" type="{}Status" minOccurs="0"/>
 *         &lt;element name="Fare" type="{}Fare" minOccurs="0"/>
 *         &lt;element name="TotalFare" type="{}Fare" minOccurs="0"/>
 *         &lt;element name="EstimatedTotalFare" type="{}Fare" minOccurs="0"/>
 *         &lt;element name="creditCardGuarantee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;sequence>
 *           &lt;element name="RateChangeInfos" type="{}RateChangeInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element name="rateDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rateCategory" type="{}RateCategories" minOccurs="0"/>
 *         &lt;element name="ExtraPersonRate" type="{}Fare" minOccurs="0"/>
 *         &lt;element name="reservationName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isPassive" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cancellationPolicy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="frequentStaysID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="frequentStaysProgram" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="frequentFlyerNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="frequentFlyerProgram" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="corporateDiscountNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rateCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ratePlan" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="taxInformation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="commissionInformation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serviceChargeText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="depositText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isMultiDateRate" type="{}Trinary" minOccurs="0"/>
 *         &lt;element name="multilevelRateCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="advanceDeposit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dcsAuxRequestReturnRate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rateChangeDuringStay" type="{}Trinary" minOccurs="0"/>
 *         &lt;element name="numberOfRollawayChildBeds" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numberOfRollawayAdultBeds" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numberOfCribs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="segmentRemarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Hotel", propOrder = {
    "bookingSiteConfNum",
    "bookingSiteURL",
    "bookingSource",
    "supplierPhone",
    "hotel",
    "roomInfo",
    "status",
    "fare",
    "totalFare",
    "estimatedTotalFare",
    "creditCardGuarantee",
    "rateChangeInfos",
    "rateDescription",
    "rateCategory",
    "extraPersonRate",
    "reservationName",
    "isPassive",
    "cancellationPolicy",
    "frequentStaysID",
    "frequentStaysProgram",
    "frequentFlyerNumber",
    "frequentFlyerProgram",
    "corporateDiscountNumber",
    "rateCode",
    "ratePlan",
    "taxInformation",
    "commissionInformation",
    "serviceChargeText",
    "depositText",
    "isMultiDateRate",
    "multilevelRateCode",
    "advanceDeposit",
    "dcsAuxRequestReturnRate",
    "rateChangeDuringStay",
    "numberOfRollawayChildBeds",
    "numberOfRollawayAdultBeds",
    "numberOfCribs",
    "segmentRemarks",
    "notes"
})
public class Hotel
    extends Segment
{

    @XmlElement(required = true)
    protected String bookingSiteConfNum;
    protected String bookingSiteURL;
    protected String bookingSource;
    protected String supplierPhone;
    @XmlElement(name = "Hotel")
    protected HotelInfo hotel;
    @XmlElement(name = "RoomInfo")
    protected RoomInfo roomInfo;
    @XmlElement(name = "Status")
    protected Status status;
    @XmlElement(name = "Fare")
    protected Fare fare;
    @XmlElement(name = "TotalFare")
    protected Fare totalFare;
    @XmlElement(name = "EstimatedTotalFare")
    protected Fare estimatedTotalFare;
    protected String creditCardGuarantee;
    @XmlElement(name = "RateChangeInfos")
    protected List<RateChangeInfo> rateChangeInfos;
    protected String rateDescription;
    protected String rateCategory;
    @XmlElement(name = "ExtraPersonRate")
    protected Fare extraPersonRate;
    protected String reservationName;
    protected String isPassive;
    protected String cancellationPolicy;
    protected String frequentStaysID;
    protected String frequentStaysProgram;
    protected String frequentFlyerNumber;
    protected String frequentFlyerProgram;
    protected String corporateDiscountNumber;
    protected String rateCode;
    protected BigInteger ratePlan;
    protected String taxInformation;
    protected String commissionInformation;
    protected String serviceChargeText;
    protected String depositText;
    protected String isMultiDateRate;
    protected String multilevelRateCode;
    protected String advanceDeposit;
    protected String dcsAuxRequestReturnRate;
    protected String rateChangeDuringStay;
    protected String numberOfRollawayChildBeds;
    protected String numberOfRollawayAdultBeds;
    protected String numberOfCribs;
    protected String segmentRemarks;
    protected String notes;

    /**
     * Gets the value of the bookingSiteConfNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingSiteConfNum() {
        return bookingSiteConfNum;
    }

    /**
     * Sets the value of the bookingSiteConfNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingSiteConfNum(String value) {
        this.bookingSiteConfNum = value;
    }

    /**
     * Gets the value of the bookingSiteURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingSiteURL() {
        return bookingSiteURL;
    }

    /**
     * Sets the value of the bookingSiteURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingSiteURL(String value) {
        this.bookingSiteURL = value;
    }

    /**
     * Gets the value of the bookingSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingSource() {
        return bookingSource;
    }

    /**
     * Sets the value of the bookingSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingSource(String value) {
        this.bookingSource = value;
    }

    /**
     * Gets the value of the supplierPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierPhone() {
        return supplierPhone;
    }

    /**
     * Sets the value of the supplierPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierPhone(String value) {
        this.supplierPhone = value;
    }

    /**
     * Gets the value of the hotel property.
     * 
     * @return
     *     possible object is
     *     {@link HotelInfo }
     *     
     */
    public HotelInfo getHotel() {
        return hotel;
    }

    /**
     * Sets the value of the hotel property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelInfo }
     *     
     */
    public void setHotel(HotelInfo value) {
        this.hotel = value;
    }

    /**
     * Gets the value of the roomInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RoomInfo }
     *     
     */
    public RoomInfo getRoomInfo() {
        return roomInfo;
    }

    /**
     * Sets the value of the roomInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoomInfo }
     *     
     */
    public void setRoomInfo(RoomInfo value) {
        this.roomInfo = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the fare property.
     * 
     * @return
     *     possible object is
     *     {@link Fare }
     *     
     */
    public Fare getFare() {
        return fare;
    }

    /**
     * Sets the value of the fare property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fare }
     *     
     */
    public void setFare(Fare value) {
        this.fare = value;
    }

    /**
     * Gets the value of the totalFare property.
     * 
     * @return
     *     possible object is
     *     {@link Fare }
     *     
     */
    public Fare getTotalFare() {
        return totalFare;
    }

    /**
     * Sets the value of the totalFare property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fare }
     *     
     */
    public void setTotalFare(Fare value) {
        this.totalFare = value;
    }

    /**
     * Gets the value of the estimatedTotalFare property.
     * 
     * @return
     *     possible object is
     *     {@link Fare }
     *     
     */
    public Fare getEstimatedTotalFare() {
        return estimatedTotalFare;
    }

    /**
     * Sets the value of the estimatedTotalFare property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fare }
     *     
     */
    public void setEstimatedTotalFare(Fare value) {
        this.estimatedTotalFare = value;
    }

    /**
     * Gets the value of the creditCardGuarantee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditCardGuarantee() {
        return creditCardGuarantee;
    }

    /**
     * Sets the value of the creditCardGuarantee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditCardGuarantee(String value) {
        this.creditCardGuarantee = value;
    }

    /**
     * Gets the value of the rateChangeInfos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rateChangeInfos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRateChangeInfos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RateChangeInfo }
     * 
     * 
     */
    public List<RateChangeInfo> getRateChangeInfos() {
        if (rateChangeInfos == null) {
            rateChangeInfos = new ArrayList<RateChangeInfo>();
        }
        return this.rateChangeInfos;
    }

    /**
     * Gets the value of the rateDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateDescription() {
        return rateDescription;
    }

    /**
     * Sets the value of the rateDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateDescription(String value) {
        this.rateDescription = value;
    }

    /**
     * Gets the value of the rateCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateCategory() {
        return rateCategory;
    }

    /**
     * Sets the value of the rateCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateCategory(String value) {
        this.rateCategory = value;
    }

    /**
     * Gets the value of the extraPersonRate property.
     * 
     * @return
     *     possible object is
     *     {@link Fare }
     *     
     */
    public Fare getExtraPersonRate() {
        return extraPersonRate;
    }

    /**
     * Sets the value of the extraPersonRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fare }
     *     
     */
    public void setExtraPersonRate(Fare value) {
        this.extraPersonRate = value;
    }

    /**
     * Gets the value of the reservationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReservationName() {
        return reservationName;
    }

    /**
     * Sets the value of the reservationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReservationName(String value) {
        this.reservationName = value;
    }

    /**
     * Gets the value of the isPassive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPassive() {
        return isPassive;
    }

    /**
     * Sets the value of the isPassive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPassive(String value) {
        this.isPassive = value;
    }

    /**
     * Gets the value of the cancellationPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancellationPolicy() {
        return cancellationPolicy;
    }

    /**
     * Sets the value of the cancellationPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancellationPolicy(String value) {
        this.cancellationPolicy = value;
    }

    /**
     * Gets the value of the frequentStaysID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequentStaysID() {
        return frequentStaysID;
    }

    /**
     * Sets the value of the frequentStaysID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequentStaysID(String value) {
        this.frequentStaysID = value;
    }

    /**
     * Gets the value of the frequentStaysProgram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequentStaysProgram() {
        return frequentStaysProgram;
    }

    /**
     * Sets the value of the frequentStaysProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequentStaysProgram(String value) {
        this.frequentStaysProgram = value;
    }

    /**
     * Gets the value of the frequentFlyerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequentFlyerNumber() {
        return frequentFlyerNumber;
    }

    /**
     * Sets the value of the frequentFlyerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequentFlyerNumber(String value) {
        this.frequentFlyerNumber = value;
    }

    /**
     * Gets the value of the frequentFlyerProgram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequentFlyerProgram() {
        return frequentFlyerProgram;
    }

    /**
     * Sets the value of the frequentFlyerProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequentFlyerProgram(String value) {
        this.frequentFlyerProgram = value;
    }

    /**
     * Gets the value of the corporateDiscountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorporateDiscountNumber() {
        return corporateDiscountNumber;
    }

    /**
     * Sets the value of the corporateDiscountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorporateDiscountNumber(String value) {
        this.corporateDiscountNumber = value;
    }

    /**
     * Gets the value of the rateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateCode() {
        return rateCode;
    }

    /**
     * Sets the value of the rateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateCode(String value) {
        this.rateCode = value;
    }

    /**
     * Gets the value of the ratePlan property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRatePlan() {
        return ratePlan;
    }

    /**
     * Sets the value of the ratePlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRatePlan(BigInteger value) {
        this.ratePlan = value;
    }

    /**
     * Gets the value of the taxInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxInformation() {
        return taxInformation;
    }

    /**
     * Sets the value of the taxInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxInformation(String value) {
        this.taxInformation = value;
    }

    /**
     * Gets the value of the commissionInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommissionInformation() {
        return commissionInformation;
    }

    /**
     * Sets the value of the commissionInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommissionInformation(String value) {
        this.commissionInformation = value;
    }

    /**
     * Gets the value of the serviceChargeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceChargeText() {
        return serviceChargeText;
    }

    /**
     * Sets the value of the serviceChargeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceChargeText(String value) {
        this.serviceChargeText = value;
    }

    /**
     * Gets the value of the depositText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepositText() {
        return depositText;
    }

    /**
     * Sets the value of the depositText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepositText(String value) {
        this.depositText = value;
    }

    /**
     * Gets the value of the isMultiDateRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsMultiDateRate() {
        return isMultiDateRate;
    }

    /**
     * Sets the value of the isMultiDateRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsMultiDateRate(String value) {
        this.isMultiDateRate = value;
    }

    /**
     * Gets the value of the multilevelRateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultilevelRateCode() {
        return multilevelRateCode;
    }

    /**
     * Sets the value of the multilevelRateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultilevelRateCode(String value) {
        this.multilevelRateCode = value;
    }

    /**
     * Gets the value of the advanceDeposit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvanceDeposit() {
        return advanceDeposit;
    }

    /**
     * Sets the value of the advanceDeposit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvanceDeposit(String value) {
        this.advanceDeposit = value;
    }

    /**
     * Gets the value of the dcsAuxRequestReturnRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDcsAuxRequestReturnRate() {
        return dcsAuxRequestReturnRate;
    }

    /**
     * Sets the value of the dcsAuxRequestReturnRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDcsAuxRequestReturnRate(String value) {
        this.dcsAuxRequestReturnRate = value;
    }

    /**
     * Gets the value of the rateChangeDuringStay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateChangeDuringStay() {
        return rateChangeDuringStay;
    }

    /**
     * Sets the value of the rateChangeDuringStay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateChangeDuringStay(String value) {
        this.rateChangeDuringStay = value;
    }

    /**
     * Gets the value of the numberOfRollawayChildBeds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfRollawayChildBeds() {
        return numberOfRollawayChildBeds;
    }

    /**
     * Sets the value of the numberOfRollawayChildBeds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfRollawayChildBeds(String value) {
        this.numberOfRollawayChildBeds = value;
    }

    /**
     * Gets the value of the numberOfRollawayAdultBeds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfRollawayAdultBeds() {
        return numberOfRollawayAdultBeds;
    }

    /**
     * Sets the value of the numberOfRollawayAdultBeds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfRollawayAdultBeds(String value) {
        this.numberOfRollawayAdultBeds = value;
    }

    /**
     * Gets the value of the numberOfCribs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfCribs() {
        return numberOfCribs;
    }

    /**
     * Sets the value of the numberOfCribs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfCribs(String value) {
        this.numberOfCribs = value;
    }

    /**
     * Gets the value of the segmentRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegmentRemarks() {
        return segmentRemarks;
    }

    /**
     * Sets the value of the segmentRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegmentRemarks(String value) {
        this.segmentRemarks = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

}
