//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.02 at 10:16:47 AM IST 
//


package com.bcd.bdu.model.bookingdata.db;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bcd.bdu.model.bookingdata.db package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bcd.bdu.model.bookingdata.db
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PNR }
     * 
     */
    public PNR createPNR() {
        return new PNR();
    }

    /**
     * Create an instance of {@link PNR.TicketInfos }
     * 
     */
    public PNR.TicketInfos createPNRTicketInfos() {
        return new PNR.TicketInfos();
    }

    /**
     * Create an instance of {@link PNR.TicketInfos.TicketInfo }
     * 
     */
    public PNR.TicketInfos.TicketInfo createPNRTicketInfosTicketInfo() {
        return new PNR.TicketInfos.TicketInfo();
    }

    /**
     * Create an instance of {@link PNR.TicketRequests }
     * 
     */
    public PNR.TicketRequests createPNRTicketRequests() {
        return new PNR.TicketRequests();
    }

    /**
     * Create an instance of {@link PNR.StoredFares }
     * 
     */
    public PNR.StoredFares createPNRStoredFares() {
        return new PNR.StoredFares();
    }

    /**
     * Create an instance of {@link PNR.StoredFares.StoredFare }
     * 
     */
    public PNR.StoredFares.StoredFare createPNRStoredFaresStoredFare() {
        return new PNR.StoredFares.StoredFare();
    }

    /**
     * Create an instance of {@link PNR.StoredFares.StoredFare.CreditCard }
     * 
     */
    public PNR.StoredFares.StoredFare.CreditCard createPNRStoredFaresStoredFareCreditCard() {
        return new PNR.StoredFares.StoredFare.CreditCard();
    }

    /**
     * Create an instance of {@link PNR.StoredFares.StoredFare.StoredFarePassengers }
     * 
     */
    public PNR.StoredFares.StoredFare.StoredFarePassengers createPNRStoredFaresStoredFareStoredFarePassengers() {
        return new PNR.StoredFares.StoredFare.StoredFarePassengers();
    }

    /**
     * Create an instance of {@link PNR.StoredFares.StoredFare.StoredFarePassengers.StoredFarePassenger }
     * 
     */
    public PNR.StoredFares.StoredFare.StoredFarePassengers.StoredFarePassenger createPNRStoredFaresStoredFareStoredFarePassengersStoredFarePassenger() {
        return new PNR.StoredFares.StoredFare.StoredFarePassengers.StoredFarePassenger();
    }

    /**
     * Create an instance of {@link PNR.StoredFares.StoredFare.StoredFareSegments }
     * 
     */
    public PNR.StoredFares.StoredFare.StoredFareSegments createPNRStoredFaresStoredFareStoredFareSegments() {
        return new PNR.StoredFares.StoredFare.StoredFareSegments();
    }

    /**
     * Create an instance of {@link PNR.SSRs }
     * 
     */
    public PNR.SSRs createPNRSSRs() {
        return new PNR.SSRs();
    }

    /**
     * Create an instance of {@link PNR.Remarks }
     * 
     */
    public PNR.Remarks createPNRRemarks() {
        return new PNR.Remarks();
    }

    /**
     * Create an instance of {@link PNR.Contacts }
     * 
     */
    public PNR.Contacts createPNRContacts() {
        return new PNR.Contacts();
    }

    /**
     * Create an instance of {@link PNR.Contacts.EmailAddresses }
     * 
     */
    public PNR.Contacts.EmailAddresses createPNRContactsEmailAddresses() {
        return new PNR.Contacts.EmailAddresses();
    }

    /**
     * Create an instance of {@link PNR.Contacts.PhoneNumbers }
     * 
     */
    public PNR.Contacts.PhoneNumbers createPNRContactsPhoneNumbers() {
        return new PNR.Contacts.PhoneNumbers();
    }

    /**
     * Create an instance of {@link PNR.Travelers }
     * 
     */
    public PNR.Travelers createPNRTravelers() {
        return new PNR.Travelers();
    }

    /**
     * Create an instance of {@link PNR.Travelers.Traveler }
     * 
     */
    public PNR.Travelers.Traveler createPNRTravelersTraveler() {
        return new PNR.Travelers.Traveler();
    }

    /**
     * Create an instance of {@link PNR.Travelers.Traveler.Seats }
     * 
     */
    public PNR.Travelers.Traveler.Seats createPNRTravelersTravelerSeats() {
        return new PNR.Travelers.Traveler.Seats();
    }

    /**
     * Create an instance of {@link PNR.Travelers.Traveler.SeatPreferenceInfo }
     * 
     */
    public PNR.Travelers.Traveler.SeatPreferenceInfo createPNRTravelersTravelerSeatPreferenceInfo() {
        return new PNR.Travelers.Traveler.SeatPreferenceInfo();
    }

    /**
     * Create an instance of {@link PNR.Travelers.Traveler.MealPreferenceInfo }
     * 
     */
    public PNR.Travelers.Traveler.MealPreferenceInfo createPNRTravelersTravelerMealPreferenceInfo() {
        return new PNR.Travelers.Traveler.MealPreferenceInfo();
    }

    /**
     * Create an instance of {@link PNR.Travelers.Traveler.FrequentFlyerInfo }
     * 
     */
    public PNR.Travelers.Traveler.FrequentFlyerInfo createPNRTravelersTravelerFrequentFlyerInfo() {
        return new PNR.Travelers.Traveler.FrequentFlyerInfo();
    }

    /**
     * Create an instance of {@link PNR.Identification }
     * 
     */
    public PNR.Identification createPNRIdentification() {
        return new PNR.Identification();
    }

    /**
     * Create an instance of {@link PNR.BillingAddress }
     * 
     */
    public PNR.BillingAddress createPNRBillingAddress() {
        return new PNR.BillingAddress();
    }

    /**
     * Create an instance of {@link PNR.DeliveryAddress }
     * 
     */
    public PNR.DeliveryAddress createPNRDeliveryAddress() {
        return new PNR.DeliveryAddress();
    }

    /**
     * Create an instance of {@link PNR.Segments }
     * 
     */
    public PNR.Segments createPNRSegments() {
        return new PNR.Segments();
    }

    /**
     * Create an instance of {@link HotelInfo }
     * 
     */
    public HotelInfo createHotelInfo() {
        return new HotelInfo();
    }

    /**
     * Create an instance of {@link ClassOfService }
     * 
     */
    public ClassOfService createClassOfService() {
        return new ClassOfService();
    }

    /**
     * Create an instance of {@link RoomInfo }
     * 
     */
    public RoomInfo createRoomInfo() {
        return new RoomInfo();
    }

    /**
     * Create an instance of {@link TourCarrier }
     * 
     */
    public TourCarrier createTourCarrier() {
        return new TourCarrier();
    }

    /**
     * Create an instance of {@link Rail }
     * 
     */
    public Rail createRail() {
        return new Rail();
    }

    /**
     * Create an instance of {@link IntegerList }
     * 
     */
    public IntegerList createIntegerList() {
        return new IntegerList();
    }

    /**
     * Create an instance of {@link MealInfo }
     * 
     */
    public MealInfo createMealInfo() {
        return new MealInfo();
    }

    /**
     * Create an instance of {@link Carrier }
     * 
     */
    public Carrier createCarrier() {
        return new Carrier();
    }

    /**
     * Create an instance of {@link RailInfo }
     * 
     */
    public RailInfo createRailInfo() {
        return new RailInfo();
    }

    /**
     * Create an instance of {@link Tour }
     * 
     */
    public Tour createTour() {
        return new Tour();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link Bus }
     * 
     */
    public Bus createBus() {
        return new Bus();
    }

    /**
     * Create an instance of {@link com.bcd.bdu.model.bookingdata.db.TicketInfo }
     * 
     */
    public com.bcd.bdu.model.bookingdata.db.TicketInfo createTicketInfo() {
        return new com.bcd.bdu.model.bookingdata.db.TicketInfo();
    }

    /**
     * Create an instance of {@link CruiseFerry }
     * 
     */
    public CruiseFerry createCruiseFerry() {
        return new CruiseFerry();
    }

    /**
     * Create an instance of {@link StringList }
     * 
     */
    public StringList createStringList() {
        return new StringList();
    }

    /**
     * Create an instance of {@link ShipInfo }
     * 
     */
    public ShipInfo createShipInfo() {
        return new ShipInfo();
    }

    /**
     * Create an instance of {@link Air }
     * 
     */
    public Air createAir() {
        return new Air();
    }

    /**
     * Create an instance of {@link CarFare }
     * 
     */
    public CarFare createCarFare() {
        return new CarFare();
    }

    /**
     * Create an instance of {@link Fare }
     * 
     */
    public Fare createFare() {
        return new Fare();
    }

    /**
     * Create an instance of {@link AddressInfo }
     * 
     */
    public AddressInfo createAddressInfo() {
        return new AddressInfo();
    }

    /**
     * Create an instance of {@link FlightInfo }
     * 
     */
    public FlightInfo createFlightInfo() {
        return new FlightInfo();
    }

    /**
     * Create an instance of {@link CarInfo }
     * 
     */
    public CarInfo createCarInfo() {
        return new CarInfo();
    }

    /**
     * Create an instance of {@link Car }
     * 
     */
    public Car createCar() {
        return new Car();
    }

    /**
     * Create an instance of {@link AirportInfo }
     * 
     */
    public AirportInfo createAirportInfo() {
        return new AirportInfo();
    }

    /**
     * Create an instance of {@link CruiseInfo }
     * 
     */
    public CruiseInfo createCruiseInfo() {
        return new CruiseInfo();
    }

    /**
     * Create an instance of {@link RateChangeInfo }
     * 
     */
    public RateChangeInfo createRateChangeInfo() {
        return new RateChangeInfo();
    }

    /**
     * Create an instance of {@link Hotel }
     * 
     */
    public Hotel createHotel() {
        return new Hotel();
    }

    /**
     * Create an instance of {@link PNR.TicketInfos.TicketInfo.BaseFare }
     * 
     */
    public PNR.TicketInfos.TicketInfo.BaseFare createPNRTicketInfosTicketInfoBaseFare() {
        return new PNR.TicketInfos.TicketInfo.BaseFare();
    }

    /**
     * Create an instance of {@link PNR.TicketInfos.TicketInfo.FareTotal }
     * 
     */
    public PNR.TicketInfos.TicketInfo.FareTotal createPNRTicketInfosTicketInfoFareTotal() {
        return new PNR.TicketInfos.TicketInfo.FareTotal();
    }

    /**
     * Create an instance of {@link PNR.TicketRequests.TicketRequest }
     * 
     */
    public PNR.TicketRequests.TicketRequest createPNRTicketRequestsTicketRequest() {
        return new PNR.TicketRequests.TicketRequest();
    }

    /**
     * Create an instance of {@link PNR.StoredFares.StoredFare.BaseFare }
     * 
     */
    public PNR.StoredFares.StoredFare.BaseFare createPNRStoredFaresStoredFareBaseFare() {
        return new PNR.StoredFares.StoredFare.BaseFare();
    }

    /**
     * Create an instance of {@link PNR.StoredFares.StoredFare.TotalFare }
     * 
     */
    public PNR.StoredFares.StoredFare.TotalFare createPNRStoredFaresStoredFareTotalFare() {
        return new PNR.StoredFares.StoredFare.TotalFare();
    }

    /**
     * Create an instance of {@link PNR.StoredFares.StoredFare.EquivalentFare }
     * 
     */
    public PNR.StoredFares.StoredFare.EquivalentFare createPNRStoredFaresStoredFareEquivalentFare() {
        return new PNR.StoredFares.StoredFare.EquivalentFare();
    }

    /**
     * Create an instance of {@link PNR.StoredFares.StoredFare.CreditCard.Amount }
     * 
     */
    public PNR.StoredFares.StoredFare.CreditCard.Amount createPNRStoredFaresStoredFareCreditCardAmount() {
        return new PNR.StoredFares.StoredFare.CreditCard.Amount();
    }

    /**
     * Create an instance of {@link PNR.StoredFares.StoredFare.StoredFarePassengers.StoredFarePassenger.BaseFare }
     * 
     */
    public PNR.StoredFares.StoredFare.StoredFarePassengers.StoredFarePassenger.BaseFare createPNRStoredFaresStoredFareStoredFarePassengersStoredFarePassengerBaseFare() {
        return new PNR.StoredFares.StoredFare.StoredFarePassengers.StoredFarePassenger.BaseFare();
    }

    /**
     * Create an instance of {@link PNR.StoredFares.StoredFare.StoredFarePassengers.StoredFarePassenger.TotalFare }
     * 
     */
    public PNR.StoredFares.StoredFare.StoredFarePassengers.StoredFarePassenger.TotalFare createPNRStoredFaresStoredFareStoredFarePassengersStoredFarePassengerTotalFare() {
        return new PNR.StoredFares.StoredFare.StoredFarePassengers.StoredFarePassenger.TotalFare();
    }

    /**
     * Create an instance of {@link PNR.StoredFares.StoredFare.StoredFareSegments.StoredFareSegment }
     * 
     */
    public PNR.StoredFares.StoredFare.StoredFareSegments.StoredFareSegment createPNRStoredFaresStoredFareStoredFareSegmentsStoredFareSegment() {
        return new PNR.StoredFares.StoredFare.StoredFareSegments.StoredFareSegment();
    }

    /**
     * Create an instance of {@link PNR.SSRs.SSR }
     * 
     */
    public PNR.SSRs.SSR createPNRSSRsSSR() {
        return new PNR.SSRs.SSR();
    }

    /**
     * Create an instance of {@link PNR.Remarks.Remark }
     * 
     */
    public PNR.Remarks.Remark createPNRRemarksRemark() {
        return new PNR.Remarks.Remark();
    }

    /**
     * Create an instance of {@link PNR.Contacts.EmailAddresses.EmailAddress }
     * 
     */
    public PNR.Contacts.EmailAddresses.EmailAddress createPNRContactsEmailAddressesEmailAddress() {
        return new PNR.Contacts.EmailAddresses.EmailAddress();
    }

    /**
     * Create an instance of {@link PNR.Contacts.PhoneNumbers.PhoneNumber }
     * 
     */
    public PNR.Contacts.PhoneNumbers.PhoneNumber createPNRContactsPhoneNumbersPhoneNumber() {
        return new PNR.Contacts.PhoneNumbers.PhoneNumber();
    }

    /**
     * Create an instance of {@link PNR.Travelers.Traveler.Name }
     * 
     */
    public PNR.Travelers.Traveler.Name createPNRTravelersTravelerName() {
        return new PNR.Travelers.Traveler.Name();
    }

    /**
     * Create an instance of {@link PNR.Travelers.Traveler.Seats.Seat }
     * 
     */
    public PNR.Travelers.Traveler.Seats.Seat createPNRTravelersTravelerSeatsSeat() {
        return new PNR.Travelers.Traveler.Seats.Seat();
    }

    /**
     * Create an instance of {@link PNR.Travelers.Traveler.SeatPreferenceInfo.SeatPref }
     * 
     */
    public PNR.Travelers.Traveler.SeatPreferenceInfo.SeatPref createPNRTravelersTravelerSeatPreferenceInfoSeatPref() {
        return new PNR.Travelers.Traveler.SeatPreferenceInfo.SeatPref();
    }

    /**
     * Create an instance of {@link PNR.Travelers.Traveler.MealPreferenceInfo.MealPref }
     * 
     */
    public PNR.Travelers.Traveler.MealPreferenceInfo.MealPref createPNRTravelersTravelerMealPreferenceInfoMealPref() {
        return new PNR.Travelers.Traveler.MealPreferenceInfo.MealPref();
    }

    /**
     * Create an instance of {@link PNR.Travelers.Traveler.FrequentFlyerInfo.FrequentFlyer }
     * 
     */
    public PNR.Travelers.Traveler.FrequentFlyerInfo.FrequentFlyer createPNRTravelersTravelerFrequentFlyerInfoFrequentFlyer() {
        return new PNR.Travelers.Traveler.FrequentFlyerInfo.FrequentFlyer();
    }

}
