//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.02 at 10:16:47 AM IST 
//


package com.bcd.bdu.model.bookingdata.db;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TicketInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TicketInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="isTicketed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ticketNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isTicketless" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isETicket" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TicketInfo", propOrder = {

})
public class TicketInfo {

    protected String isTicketed;
    protected String ticketNumber;
    protected String isTicketless;
    protected String isETicket;

    /**
     * Gets the value of the isTicketed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsTicketed() {
        return isTicketed;
    }

    /**
     * Sets the value of the isTicketed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsTicketed(String value) {
        this.isTicketed = value;
    }

    /**
     * Gets the value of the ticketNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketNumber() {
        return ticketNumber;
    }

    /**
     * Sets the value of the ticketNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketNumber(String value) {
        this.ticketNumber = value;
    }

    /**
     * Gets the value of the isTicketless property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsTicketless() {
        return isTicketless;
    }

    /**
     * Sets the value of the isTicketless property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsTicketless(String value) {
        this.isTicketless = value;
    }

    /**
     * Gets the value of the isETicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsETicket() {
        return isETicket;
    }

    /**
     * Sets the value of the isETicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsETicket(String value) {
        this.isETicket = value;
    }

}
